"""Extended binary Golay code G24, built independently of the C++ library.

Construction (README.md section 1.2, docs/design.md T1.1):

* Start from the cyclic (23, 12, 7) binary Golay code generated by

      g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1.

  Every codeword of the cyclic code is m(x) * g(x) mod 2 for a message
  polynomial m(x) of degree <= 11.  Since deg(m) + deg(g) <= 22 < 23 the
  product already has length 23 and no reduction mod x^23 - 1 is needed.
* Append an overall parity bit as coordinate 23 -> the extended (24, 12, 8)
  Golay code with 4096 words.

Coordinate convention: bit ``i`` of a mask is coordinate ``i`` (coefficient
of x^i for i < 23); the parity bit is bit 23.
"""

from __future__ import annotations

from functools import lru_cache

__all__ = [
    "GENERATOR_POLY",
    "golay_codewords",
    "weight_distribution",
    "is_codeword",
    "octads",
    "carry_less_multiply",
]

#: g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1, bit i = coefficient of x^i.
GENERATOR_POLY: int = (1 << 11) | (1 << 10) | (1 << 6) | (1 << 5) | (1 << 4) | (1 << 2) | 1

_MASK24 = (1 << 24) - 1


def carry_less_multiply(a: int, b: int) -> int:
    """Product of two GF(2)[x] polynomials given as bit masks (bit i = x^i)."""
    out = 0
    while b:
        if b & 1:
            out ^= a
        a <<= 1
        b >>= 1
    return out


def _parity(x: int) -> int:
    """Parity (number of set bits mod 2) of a non-negative int."""
    return bin(x).count("1") & 1


@lru_cache(maxsize=None)
def _codeword_tuple() -> tuple[int, ...]:
    words = []
    for m in range(1 << 12):
        c = carry_less_multiply(m, GENERATOR_POLY)  # length-23 cyclic codeword
        assert c < (1 << 23)
        c |= _parity(c) << 23  # overall parity in coordinate 23
        words.append(c)
    words.sort()
    return tuple(words)


def golay_codewords() -> list[int]:
    """All 4096 codewords of G24 as 24-bit masks, sorted ascending.

    Bit ``i`` of a mask is coordinate ``i``; bit 23 is the parity coordinate.
    """
    return list(_codeword_tuple())


def weight_distribution(words) -> dict[int, int]:
    """Map weight -> number of words of that weight (only weights that occur)."""
    dist: dict[int, int] = {}
    for w in words:
        k = bin(w & _MASK24).count("1")
        dist[k] = dist.get(k, 0) + 1
    return dict(sorted(dist.items()))


@lru_cache(maxsize=None)
def _codeword_set() -> frozenset[int]:
    return frozenset(_codeword_tuple())


def is_codeword(mask: int) -> bool:
    """True iff ``mask`` (a 24-bit mask) is a word of G24."""
    if mask < 0 or mask > _MASK24:
        return False
    return mask in _codeword_set()


def octads() -> list[int]:
    """The 759 weight-8 codewords (octads), sorted ascending."""
    return [w for w in _codeword_tuple() if bin(w).count("1") == 8]
