"""A4 — structural characterisation of the record 496-set (docs/design.md A4).

Deterministic, end-to-end. Every printed "RESULT" line is a computed fact
(exact integer / rational arithmetic on the declared inputs); interpretation
and labels VERIFIED/CONJECTURED are in docs/reports/A4.md.

Inputs
    data/S496.txt                                   the record set (sqrt8 scaling, norm 32)
    runs/orbits/stab496/co0_stabiliser_elements.txt the 8 matrices of Stab_Co0(S)
                                                    (regenerated via python/tools/stabilizer_496.py
                                                    if absent; every defining property is
                                                    re-verified here from scratch, so nothing
                                                    is trusted from that file)
    python/kiss_ref/{golay,leech}.py                independent Golay / Leech reference
    data/scheme/intersection_numbers.json           for the +-16-free Delsarte LP (S7)

Headline structure this file establishes (see docs/reports/A4.md):
    Stab_Co0(S) = the full sign group {+-1}^3 on an orthogonal splitting
    R^24 = B1 + B2 + B3 into three 8-dim blocks with Lambda cap B_i = sqrt2 E8
    (a Turyn-type sqrt2(E8^3) sublattice of index 2^12); every s in S has
    block components of norms (16, 16, 0) up to order, S = 208 + 144 + 144
    split over the three support pairs.

Sections
    S0  basic invariants of S (Gram histogram, shapes, antipodality, 248 classes)
    S1  Stab_Co0(S) verified from scratch; the three trace+8 involutions t1, t2, t3
        with t_i t_j = -t_k; group = blockwise {+-1}^3
    S2  the three 8-dim blocks: Lambda cap B_i = sqrt2 E8 (exact identification);
        pair lattices Lambda cap (B_j + B_k); glue indices and Smith forms
    S3  block-norm patterns of all 196560 minimal vectors; where S sits;
        hypothesis "S = all pattern vectors?"; per-pair availability counts
    S4  S in Lambda/2Lambda (248 distinct classes, GF(2) rank, coset-union test);
        the 124 orbits -> type-4 crosses; half-vector (glue) structure
    S5  sublattices generated by S, by each frame, by the 80 tightness-4
        vertices, by the 248 orbit-sum vectors (rank, index, Smith form)
    S6  the frames (24-cliques of the class orthogonality graph), maximal
        cliques, octad incidence masks -> is the span the Golay code?; frame
        vs block-support interplay
    S7  tightness / +-16-free structure: S is maximal +-16-free; two-point
        Delsarte LP with a_16 = a_-16 = 0 (exact rational value)
    S8  numerology audit (31, 2^4*31, dim E8) — honest checks only

Run:  .venv/bin/python python/tools/structure_496.py
Writes runs/a4/summary.json plus per-section artefacts in runs/a4/.
"""

from __future__ import annotations

import json
import os
import sys
import time
from collections import Counter
from itertools import combinations

import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "python"))

from kiss_ref.leech import leech_min_vectors, is_lattice_vector_rows  # noqa: E402

RUNS = os.path.join(ROOT, "runs", "a4")
os.makedirs(RUNS, exist_ok=True)

SUMMARY: dict = {}


def result(section: str, **kv):
    parts = " ".join(f"{k}={v}" for k, v in kv.items())
    print(f"RESULT section={section} {parts}")
    SUMMARY.setdefault(section, []).append({k: (v if isinstance(v, (int, str, bool)) else str(v))
                                            for k, v in kv.items()})


# --------------------------------------------------------------------- integer linear algebra

def extgcd(a: int, b: int) -> tuple[int, int, int]:
    """g, x, y with x*a + y*b = g = gcd(a, b) >= 0."""
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t


class Echelon:
    """Row echelon over Z by unimodular row operations, restricted to the first
    `ncols` columns (extra columns are carried along, e.g. a transform tail).

    insert(row) returns None if the row created a new pivot, else the fully
    reduced row (zero in the first ncols columns; its tail is a left-kernel
    contribution when the tails started as unit vectors)."""

    def __init__(self, ncols: int):
        self.ncols = ncols
        self.pivots: dict[int, list[int]] = {}

    def insert(self, row):
        r = [int(v) for v in row]
        n = self.ncols
        for c in range(n):
            if r[c] == 0:
                continue
            p = self.pivots.get(c)
            if p is None:
                self.pivots[c] = r
                return None
            a, b = p[c], r[c]
            g, x, y = extgcd(a, b)
            newp = [x * pi + y * ri for pi, ri in zip(p, r)]
            r = [(a // g) * ri - (b // g) * pi for pi, ri in zip(p, r)]
            self.pivots[c] = newp
        return r

    def det_first_block(self) -> int:
        if len(self.pivots) < self.ncols:
            return 0
        d = 1
        for c in range(self.ncols):
            d *= abs(self.pivots[c][c])
        return d

    def hnf_rows(self) -> list[list[int]]:
        """Pivot rows in column order, pivots positive, entries above pivots
        reduced — the row HNF of the inserted lattice."""
        cols = sorted(self.pivots)
        rows = []
        for c in cols:
            r = self.pivots[c][:]
            if r[c] < 0:
                r = [-v for v in r]
            rows.append(r)
        for j in range(len(rows)):
            for i in range(j + 1, len(rows)):
                c = cols[i]
                p = rows[i][c]
                q = rows[j][c] // p
                if q:
                    rows[j] = [vj - q * vi for vj, vi in zip(rows[j], rows[i])]
        return rows


def lattice_hnf(rows) -> tuple[list[list[int]], int]:
    """Row HNF of the lattice generated by integer rows; (hnf rows, index) with
    index = product of pivots if full column rank, else 0."""
    rows = np.asarray(rows)
    ech = Echelon(rows.shape[1])
    for r in rows:
        ech.insert(r)
    return ech.hnf_rows(), ech.det_first_block()


def left_kernel(A) -> list[list[int]]:
    """Basis (exact, saturated) of {c in Z^m : c A = 0} for an m x n integer
    matrix A, via unimodular row reduction of [A | I]."""
    A = [[int(v) for v in row] for row in A]
    m, n = len(A), len(A[0])
    ech = Echelon(n)
    kern = []
    for i in range(m):
        tail = [0] * m
        tail[i] = 1
        out = ech.insert(A[i] + tail)
        if out is not None:
            kern.append(out[n:])
    return kern


def int_det(M) -> int:
    """Exact determinant of a square integer matrix (fraction-free Bareiss)."""
    a = [[int(v) for v in row] for row in M]
    n = len(a)
    sign = 1
    prev = 1
    for k in range(n - 1):
        if a[k][k] == 0:
            for i in range(k + 1, n):
                if a[i][k]:
                    a[k], a[i] = a[i], a[k]
                    sign = -sign
                    break
            else:
                return 0
        for i in range(k + 1, n):
            for j in range(k + 1, n):
                a[i][j] = (a[i][j] * a[k][k] - a[i][k] * a[k][j]) // prev
        prev = a[k][k]
    return sign * a[n - 1][n - 1]


def smith_invariants(rows) -> list[int]:
    """Nontrivial invariant factors of Z^n / (lattice generated by rows)."""
    import sympy
    from sympy.matrices.normalforms import smith_normal_form

    H, idx = lattice_hnf(rows)
    assert idx != 0, "smith_invariants expects a full-rank lattice"
    snf = smith_normal_form(sympy.Matrix(H))
    diag = [int(snf[i, i]) for i in range(snf.rows)]
    return [d for d in diag if d != 1]


def short_vectors_count(G, bound: int) -> dict[int, int]:
    """Histogram {norm: count} of nonzero lattice vectors with norm <= bound
    for integer Gram G (counting +-v as 2): Fincke-Pohst on a float Cholesky
    factor, every candidate re-checked with exact integer arithmetic."""
    G = np.asarray(G, dtype=np.int64)
    n = G.shape[0]
    L = np.linalg.cholesky(G.astype(np.float64))
    R = L.T
    hist: dict[int, int] = {}
    x = np.zeros(n, dtype=np.int64)

    def rec(k: int, partial: np.ndarray, rem: float):
        if k < 0:
            nrm = int(x @ G @ x)
            if 0 < nrm <= bound:
                hist[nrm] = hist.get(nrm, 0) + 1
            return
        rkk = R[k, k]
        centre = -partial[k] / rkk
        half = (max(rem, 0.0) ** 0.5) / rkk + 1e-6
        lo = int(np.ceil(centre - half))
        hi = int(np.floor(centre + half))
        for xv in range(lo, hi + 1):
            x[k] = xv
            t = rkk * xv + partial[k]
            rem2 = rem - t * t
            if rem2 < -0.5:
                x[k] = 0
                continue
            rec(k - 1, partial + R[:, k] * xv, max(rem2, 0.0))
        x[k] = 0

    # slack 0.9: every candidate is re-checked exactly, so slop cannot overcount
    rec(n - 1, np.zeros(n), float(bound) + 0.9)
    return dict(sorted(hist.items()))


def gf2_span(masks) -> list[int]:
    basis: list[int] = []
    for m in masks:
        for b in basis:
            m = min(m, m ^ b)
        if m:
            basis.append(m)
            basis.sort(reverse=True)
    return basis


def gf2_rank(masks) -> int:
    return len(gf2_span(masks))


def apair_key(v) -> tuple:
    """Canonical key for the antipodal pair {v, -v} (lexicographic min)."""
    a = tuple(int(x) for x in v)
    b = tuple(-x for x in a)
    return min(a, b)


# --------------------------------------------------------------------- inputs

def load_S() -> np.ndarray:
    rows = []
    with open(os.path.join(ROOT, "data", "S496.txt")) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            rows.append([int(v) for v in line.split()])
    S = np.array(rows, dtype=np.int64)
    assert S.shape == (496, 24)
    return S


def load_stab_elements() -> list[np.ndarray]:
    path = os.path.join(ROOT, "runs", "orbits", "stab496", "co0_stabiliser_elements.txt")
    if not os.path.exists(path):
        import subprocess
        print("stabiliser file missing; regenerating via python/tools/stabilizer_496.py ...")
        subprocess.run([sys.executable, os.path.join(ROOT, "python", "tools", "stabilizer_496.py"),
                        os.path.join(ROOT, "data", "S496.txt"),
                        "--out", os.path.join(ROOT, "runs", "orbits", "stab496")],
                       check=True, cwd=ROOT)
    mats, cur = [], []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                if cur:
                    mats.append(np.array(cur, dtype=np.int64))
                    cur = []
                continue
            cur.append([int(v) for v in line.split()])
    if cur:
        mats.append(np.array(cur, dtype=np.int64))
    assert len(mats) == 8 and all(m.shape == (24, 24) for m in mats)
    return mats


# --------------------------------------------------------------------- sections

def s0_basic(S: np.ndarray, V: np.ndarray, vindex: dict):
    t0 = time.time()
    G = S @ S.T
    assert np.all(np.diag(G) == 32)
    off = G[~np.eye(496, dtype=bool)]
    vals, counts = np.unique(off, return_counts=True)
    hist = {int(v): int(c) for v, c in zip(vals, counts)}
    assert hist == {-32: 496, -8: 75008, 0: 95008, 8: 75008}, hist
    pair_hist = {v: c // 2 for v, c in hist.items()}
    assert pair_hist == {-32: 248, -8: 37504, 0: 47504, 8: 37504}
    assert all(bytes(r.astype(np.int8)) in vindex for r in S)
    assert np.all(is_lattice_vector_rows(S))
    sset = {bytes(r.astype(np.int8)) for r in S}
    assert all(bytes((-r).astype(np.int8)) in sset for r in S)
    maxabs = np.max(np.abs(S), axis=1)
    shapes = (int(np.sum(maxabs == 2)), int(np.sum(maxabs == 3)), int(np.sum(maxabs == 4)))
    assert shapes == (258, 232, 6)
    result("S0", size=496, gram_offdiag_pairs="{-32:248,-8:37504,0:47504,8:37504}",
           avoids_dot="+16 and -16", shapes=f"octad={shapes[0]},31={shapes[1]},44={shapes[2]}",
           antipodal=True, classes=248, seconds=round(time.time() - t0, 1))


def s1_stabiliser(S: np.ndarray, V: np.ndarray, vindex: dict):
    """Verify the 8 stabiliser matrices from scratch and identify the block
    structure: three trace+8 involutions t1, t2, t3 with t_i t_j = -t_k."""
    t0 = time.time()
    mats = load_stab_elements()
    sset = {bytes(r.astype(np.int8)) for r in S}
    Vsorted = np.unique(V, axis=0)
    for M in mats:
        assert np.array_equal(M @ M.T, 64 * np.eye(24, dtype=np.int64))  # orthogonal * 8
        img = V @ M.T
        assert np.all(img % 8 == 0)
        img = img // 8
        assert np.array_equal(np.unique(img, axis=0), Vsorted)  # preserves the 196560 min vectors
        simg = S @ M.T
        assert np.all(simg % 8 == 0)
        assert all(bytes(r.astype(np.int8)) in sset for r in simg // 8)  # fixes S setwise
    elems = {M.tobytes() for M in mats}
    assert len(elems) == 8
    for A in mats:
        for Bm in mats:
            P = A @ Bm
            assert np.all(P % 8 == 0) and (P // 8).tobytes() in elems  # closure
            assert np.array_equal(A @ Bm, Bm @ A)  # abelian
    traces = sorted(int(np.trace(M)) // 8 for M in mats)
    assert traces == [-24, -8, -8, -8, 8, 8, 8, 24]
    t8 = [M for M in mats if np.trace(M) == 64]

    def fixed_count(M):
        return int(np.sum(np.all((S @ M.T) // 8 == S, axis=1)))

    # deterministic order: t1 = the one fixing 208 vectors of S; t2, t3 the two
    # fixing 144, ordered by matrix bytes
    t8.sort(key=lambda M: (-fixed_count(M), M.tobytes()))
    t1, t2, t3 = t8
    fc = [fixed_count(M) for M in t8]
    assert fc == [208, 144, 144]
    for (i, j, k) in [(0, 1, 2), (0, 2, 1), (1, 2, 0)]:
        assert np.array_equal((t8[i] @ t8[j]) // 8, -t8[k])  # t_i t_j = -t_k
    monomial = lambda M: bool(np.all(np.sum(M != 0, axis=1) == 1))
    assert not any(monomial(M) for M in t8)
    result("S1", stab_order=8, structure="elementary_abelian_2^3", abelian=True,
           traces="{+24,+8x3,-8x3,-24}",
           product_rule="t_i*t_j=-t_k (NOT t_k): the three trace+8 involutions do not form a Klein group",
           group_is="blockwise {+-1}^3 on three 8-dim blocks (see S2)",
           fixed_on_S="t1:208,t2:144,t3:144", nonmonomial=True,
           lambda_preserved=True, s_preserved=True, seconds=round(time.time() - t0, 1))
    return t1, t2, t3


def build_basis(V: np.ndarray):
    """Basis B (rows) of Lambda (sqrt8 scaling) from the minimal vectors,
    certified by |det B| = 8^12 (Leech det Gram = 8^24 in this scaling)."""
    t0 = time.time()
    ech = Echelon(24)
    target = 8 ** 12
    fed = 0
    for r in V:
        ech.insert(r)
        fed += 1
        if fed % 64 == 0 and ech.det_first_block() == target:
            break
    assert ech.det_first_block() == target, ech.det_first_block()
    B = np.array(ech.hnf_rows(), dtype=np.int64)
    d = int_det(B)
    assert abs(d) == target
    import sympy
    Binv = sympy.Matrix(B.tolist()).inv()
    IB8 = 8 * Binv
    assert all(x == int(x) for x in IB8)
    IB8 = np.array([[int(IB8[i, j]) for j in range(24)] for i in range(24)], dtype=np.int64)
    assert np.max(np.abs(IB8)) < 2 ** 40
    assert np.array_equal((B @ IB8) // 8, np.eye(24, dtype=np.int64))
    print(f"# basis: fed {fed} minimal vectors, |det B| = 2^36, 8*B^-1 integral, "
          f"max|8B^-1| = {np.max(np.abs(IB8))} ({time.time()-t0:.1f}s)")
    return B, IB8


def coords_of(rows: np.ndarray, IB8: np.ndarray) -> np.ndarray:
    prod = np.asarray(rows, dtype=np.int64) @ IB8
    assert np.all(prod % 8 == 0)
    return prod // 8


def s2_blocks(S, V, B, IB8, ts):
    """The three 8-dim blocks B_i = (-1)-eigenspace of t_i; Lambda cap B_i;
    identifications and glue."""
    t0 = time.time()
    I24 = np.eye(24, dtype=np.int64)

    def coord_matrix(M):
        img = B @ M.T
        assert np.all(img % 8 == 0)
        return coords_of(img // 8, IB8)

    Ps = [coord_matrix(M) for M in ts]
    for P in Ps:
        assert abs(int_det(P)) == 1

    blocks = []       # Lambda cap B_i, basis rows in ambient coordinates
    for i, P in enumerate(Ps):
        K = left_kernel(P + I24)   # negated sublattice of t_i
        Kb = np.array(K, dtype=np.int64) @ B
        assert Kb.shape[0] == 8
        blocks.append(Kb)
    # blocks are pairwise orthogonal and span R^24
    for i, j in combinations(range(3), 2):
        assert np.all(blocks[i] @ blocks[j].T == 0)
    span = np.concatenate(blocks, axis=0)
    assert int_det(span) != 0

    # identification: Lambda cap B_i = sqrt2 E8 (ours Gram/16 even unimodular)
    for i, Kb in enumerate(blocks):
        G = Kb @ Kb.T
        assert np.all(G % 16 == 0)
        G16 = G // 16
        assert int_det(G16) == 1
        assert np.all(np.diag(G16) % 2 == 0)
        hist = short_vectors_count(G, 64)
        assert min(hist) == 32 and hist[32] == 240
        result("S2a", block=i + 1, dim=8, gram_div16="integral even, det 1",
               identification="sqrt2E8 (unique 8-dim even unimodular lattice = E8)",
               shortvec_hist_ours=str(hist))

    # fixed lattices Lambda cap (B_j + B_k) = Fix(t_i)
    pairlats = []
    for i, P in enumerate(Ps):
        K = left_kernel(P - I24)
        Kb = np.array(K, dtype=np.int64) @ B
        assert Kb.shape[0] == 16
        G = Kb @ Kb.T
        assert np.all(G % 8 == 0)
        Gstd = G // 8
        det_std = int_det(Gstd)
        even = bool(np.all(np.diag(Gstd) % 2 == 0))
        pairlats.append(Kb)
        result("S2b", fix_of=f"t{i+1}", dim=16, det_std=det_std, even_std=even)

    # glue indices
    def glue(parts):
        C = coords_of(np.concatenate(parts, axis=0), IB8)
        _, idx = lattice_hnf(C)
        return idx, smith_invariants(C)

    idx3, snf3 = glue(blocks)
    result("S2c", index_sqrt2E8cubed_in_Lambda=idx3, glue_group=str(snf3),
           interpretation="Lambda contains sqrt2(E8+E8+E8) with index 2^12: Turyn-type construction")
    import math
    import sympy
    for i in range(3):
        j, k = [x for x in range(3) if x != i]
        # index and quotient of sqrt2E8 + sqrt2E8 inside the 16-dim pair
        # lattice Fix(t_i) = Lambda cap (B_j + B_k)
        Gfix = pairlats[i] @ pairlats[i].T
        det_fix = int_det(Gfix // 8)
        det_sum = 256 * 256  # det_std(sqrt2E8) = 2^8
        idx_pair = math.isqrt(det_sum // det_fix)
        assert idx_pair * idx_pair * det_fix == det_sum
        # exact quotient structure: express the block bases in the pair basis
        Pm = sympy.Matrix(pairlats[i].tolist())
        Gram = Pm * Pm.T
        X = sympy.Matrix(np.concatenate([blocks[j], blocks[k]], axis=0).tolist())
        Y = X * Pm.T * Gram.inv()
        assert all(y == int(y) for y in Y)
        Yint = [[int(Y[r, cc]) for cc in range(16)] for r in range(16)]
        snf2 = smith_invariants(Yint)
        result("S2d", pair=f"B{j+1}+B{k+1}", det_std_fix=det_fix,
               index_in_fix=idx_pair, glue_group_pair=str(snf2))
    result("S2", seconds=round(time.time() - t0, 1))
    return blocks, pairlats, Ps


def s3_patterns(S, V, ts):
    """Block-norm patterns (n1, n2, n3), n_i = |pi_i v|^2, for all 196560
    minimal vectors and for S."""
    t0 = time.time()
    Vf = V.astype(np.float64)
    dots = []
    for M in ts:
        img = (Vf @ M.T.astype(np.float64)) / 8.0
        dots.append(np.einsum("ij,ij->i", Vf, img).astype(np.int64))
    # n_i = (32 - <v, t_i v>)/2
    ns = [(32 - d) // 2 for d in dots]
    for d in dots:
        assert np.all((32 - d) % 2 == 0)
    tup = np.stack(ns, axis=1)
    assert np.all(tup.sum(axis=1) == 32)
    assert np.all(tup >= 0)
    uniq, counts = np.unique(tup, axis=0, return_counts=True)
    pattern_hist = {tuple(int(x) for x in u): int(c) for u, c in zip(uniq, counts)}
    with open(os.path.join(RUNS, "pattern_histogram.json"), "w") as f:
        json.dump({str(k): v for k, v in sorted(pattern_hist.items())}, f, indent=1)

    sset = {bytes(r.astype(np.int8)) for r in S}
    smask = np.fromiter((bytes(r) in sset for r in V.astype(np.int8)), dtype=bool, count=len(V))
    assert int(smask.sum()) == 496
    s_tup = tup[smask]
    s_uniq, s_counts = np.unique(s_tup, axis=0, return_counts=True)
    s_hist = {tuple(int(x) for x in u): int(c) for u, c in zip(s_uniq, s_counts)}

    duads = {(0, 16, 16): "s1=0(t1-fixed)", (16, 0, 16): "s2=0(t2-fixed)", (16, 16, 0): "s3=0(t3-fixed)"}
    n_duad = {k: pattern_hist.get(k, 0) for k in duads}
    s_duad = {k: s_hist.get(k, 0) for k in duads}
    # kissing number of each 16-dim pair lattice Fix(t_i): its minimal vectors
    # are the duads on that pair plus the monads of its two blocks
    for i, key in enumerate(duads):
        kiss = n_duad[key] + 2 * 240
        assert kiss == 4320
    result("S3c", pair_lattice_kissing=4320,
           identification="Fix(t_i): 16-dim even, det_std 2^8, min 4, kissing 4320 "
                          "= extremal 2-modular => Barnes-Wall BW16 (Quebbemann uniqueness)")
    result("S3a", patterns_in_S=str({str(k): v for k, v in s_hist.items()}),
           S_all_duads=bool(sum(s_duad.values()) == 496),
           lambda_min_duads=str({str(k): v for k, v in n_duad.items()}),
           total_duads=sum(n_duad.values()),
           S_fraction_of_duads=f"{496}/{sum(n_duad.values())}",
           S_equals_all_duads=bool(sum(n_duad.values()) == 496))
    whole = {(32, 0, 0): pattern_hist.get((32, 0, 0), 0),
             (0, 32, 0): pattern_hist.get((0, 32, 0), 0),
             (0, 0, 32): pattern_hist.get((0, 0, 32), 0)}
    result("S3b", full_pattern_histogram=str({str(k): v for k, v in sorted(pattern_hist.items())}),
           norm32_wholly_in_block=str({str(k): v for k, v in whole.items()}),
           n_patterns=len(pattern_hist), seconds=round(time.time() - t0, 1))
    return tup, smask, pattern_hist, s_hist


def s3e_family(ts):
    """All 64 plateau 496-sets (A1's data/S496_family/) are duad sets on the
    SAME Turyn frame (they share the stabiliser, T3.4b); record their support
    splits."""
    t0 = time.time()
    fam_dir = os.path.join(ROOT, "data", "S496_family")
    if not os.path.isdir(fam_dir):
        result("S3e", skipped="data/S496_family missing")
        return
    files = sorted(f for f in os.listdir(fam_dir) if f.startswith("S_") and f.endswith(".txt"))
    splits = Counter()
    all_duads = True
    for fn in files:
        rows = []
        with open(os.path.join(fam_dir, fn)) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    rows.append([int(v) for v in line.split()])
        X = np.array(rows, dtype=np.int64)
        assert X.shape == (496, 24)
        pats = []
        for M in ts:
            img = (X.astype(np.float64) @ M.T.astype(np.float64)) / 8.0
            d = np.einsum("ij,ij->i", X.astype(np.float64), img).astype(np.int64)
            pats.append((32 - d) // 2)
        tt = np.stack(pats, axis=1)
        okd = bool(np.all(np.sort(tt, axis=1) == np.array([0, 16, 16])))
        all_duads &= okd
        split = tuple(int(np.sum(tt[:, i] == 0)) for i in range(3))
        splits[split] += 1
    result("S3e", family_files=len(files), all_64_sets_are_duad_sets=all_duads,
           support_splits=str(dict(splits)), seconds=round(time.time() - t0, 1))


def s4_mod2(S, V, IB8, ts):
    t0 = time.time()
    CS = coords_of(S, IB8)
    pw2 = (1 << np.arange(24, dtype=np.int64))
    masks = [int(m) for m in ((CS % 2) * pw2).sum(axis=1)]
    uniq = sorted(set(masks))
    assert len(uniq) == 248
    assert all(masks.count(m) == 2 for m in uniq[:8])  # spot check; full check below
    cnt = Counter(masks)
    assert set(cnt.values()) == {2}
    rank = gf2_rank(uniq)
    cset = set(uniq)
    stab = [t for t in {uniq[0] ^ u for u in uniq} if t and all((u ^ t) in cset for u in uniq)]
    result("S4a", classes_mod2=len(uniq), all_distinct=True, gf2_rank=rank,
           coset_stabiliser_order=1 + len(stab), union_of_cosets=bool(stab))

    # orbits of the 2^3 on S
    sindex = {bytes(r.astype(np.int8)): i for i, r in enumerate(S)}
    perms = []
    for M in ts:
        img = (S @ M.T) // 8
        perms.append(np.array([sindex[bytes(r.astype(np.int8))] for r in img]))
    neg = np.array([sindex[bytes((-r).astype(np.int8))] for r in S])
    parent = list(range(496))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for p in perms + [neg]:
        for i in range(496):
            ri, rj = find(i), find(int(p[i]))
            if ri != rj:
                parent[ri] = rj
    orbit_map: dict[int, list[int]] = {}
    for i in range(496):
        orbit_map.setdefault(find(i), []).append(i)
    orbs = sorted(orbit_map.values(), key=lambda o: o[0])
    assert len(orbs) == 124 and all(len(o) == 4 for o in orbs)

    types, cross_masks, sum_vecs = [], [], []
    half_pairs = {0: [], 1: [], 2: []}   # per type: (2*s_j, 2*s_k) block components
    for o in orbs:
        x = S[o[0]]
        y = next(S[j] for j in o[1:] if not np.array_equal(S[j], -x))
        assert int(x @ y) == 0
        wp, wm = x + y, x - y
        assert int(wp @ wp) == 64 and int(wm @ wm) == 64
        cw = coords_of(wp.reshape(1, -1), IB8)[0] % 2
        cw2 = coords_of(wm.reshape(1, -1), IB8)[0] % 2
        assert np.array_equal(cw, cw2)  # x+y = x-y mod 2Lambda
        m = int((cw.astype(np.int64) * pw2).sum())
        assert m != 0
        cross_masks.append(m)
        sum_vecs.append(wp)
        sum_vecs.append(wm)
        tfix = [gi for gi, p in enumerate(perms) if p[o[0]] == o[0]]
        assert len(tfix) == 1
        types.append(tfix[0])
        half_pairs[tfix[0]].append((apair_key(wp), apair_key(wm)))
    tcount = Counter(types)
    assert dict(tcount) == {0: 52, 1: 36, 2: 36}
    n_cross = len(set(cross_masks))
    cross_mult = Counter(Counter(cross_masks).values())
    cross_rank = gf2_rank(sorted(set(cross_masks)))
    overlap = len(set(cross_masks) & set(uniq))
    per_type = {t: len({m for m, tt in zip(cross_masks, types) if tt == t}) for t in sorted(tcount)}
    cu = sorted(set(cross_masks))
    cuset = set(cu)
    cstab = [t for t in {cu[0] ^ u for u in cu} if t and all((u ^ t) in cuset for u in cu)]

    # half-vector (glue) structure: per type, distinct +-(x+y) and +-(x-y)
    half_stats = {}
    for t, prs in half_pairs.items():
        left = {p[0] for p in prs}
        right = {p[1] for p in prs}
        allv = left | right
        half_stats[t] = (len(prs), len(allv))
    result("S4b", orbits=124, orbit_types="t1-fixed:52,t2-fixed:36,t3-fixed:36",
           distinct_crosses=n_cross, cross_multiplicities=str(dict(cross_mult)),
           per_type_distinct=str(per_type), cross_gf2_rank=cross_rank,
           crosses_meet_S_classes=overlap, cross_coset_stabiliser_order=1 + len(cstab),
           halfsum_vectors_per_type=str(half_stats),
           seconds=round(time.time() - t0, 1))
    return orbs, types, cross_masks, np.array(sum_vecs), uniq


def s5_sublattices(S, IB8, frames_idx, class_reps, t4_vectors, sum_vecs):
    t0 = time.time()

    def report(name, rows):
        C = coords_of(np.asarray(rows, dtype=np.int64), IB8)
        H, idx = lattice_hnf(C)
        snf = smith_invariants(C) if idx else None
        result("S5", lattice=name, rank=len(H), index_in_Lambda=idx, quotient=str(snf))

    report("<S>_Z", S)
    for i, fidx in enumerate(frames_idx):
        report(f"frame{i}", class_reps[sorted(fidx)])
    report("tightness4_80", t4_vectors)
    report("orbit_sums_248", sum_vecs)
    result("S5", seconds=round(time.time() - t0, 1))


def s5b_min_vectors_of_gen(S, V, IB8, tup, smask, t4_vectors):
    """Decisive hypothesis test: is S the set of minimal vectors of the
    sublattice <S>_Z?  Since Lambda/<S> = (Z/2)^4, we have 2Lambda <= <S> and
    membership of v in <S> depends only on the class of v mod 2Lambda:
    v in <S>  iff  class(v) lies in the GF(2)-span W of the S-classes."""
    t0 = time.time()
    CS = coords_of(S, IB8) % 2
    pw = (1 << np.arange(24, dtype=np.int64))
    s_masks = sorted({int(m) for m in (CS * pw).sum(axis=1)})
    W = gf2_span(s_masks)
    assert len(W) == 20

    CV = coords_of(V, IB8) % 2
    v_masks = (CV * pw).sum(axis=1)

    def in_span(m):
        m = int(m)
        for bvec in W:
            m = min(m, m ^ bvec)
        return m == 0

    member = np.fromiter((in_span(m) for m in v_masks), dtype=bool, count=len(V))
    n_min = int(member.sum())
    n_in_S = int((member & smask).sum())
    assert n_in_S == 496
    # breakdown of the extra minimal vectors of <S> by block pattern
    extra = member & ~smask
    extra_tup = tup[extra]
    eu, ec = np.unique(extra_tup, axis=0, return_counts=True)
    extra_hist = {str(tuple(int(x) for x in u)): int(c) for u, c in zip(eu, ec)}
    # are the 80 tightness-4 vertices in <S>?
    C4 = coords_of(t4_vectors, IB8) % 2
    t4_masks = (C4 * pw).sum(axis=1)
    t4_in = sum(1 for m in t4_masks if in_span(m))
    result("S5b", min_vectors_of_genS=n_min, of_which_in_S=n_in_S,
           S_equals_min_of_genS=bool(n_min == 496),
           extra_min_vectors=n_min - 496, extra_by_pattern=str(extra_hist),
           t4_in_genS=t4_in, seconds=round(time.time() - t0, 1))
    return member


def short_vectors_list(G, bound: int):
    """All nonzero coefficient vectors with norm <= bound (both signs)."""
    G = np.asarray(G, dtype=np.int64)
    n = G.shape[0]
    R = np.linalg.cholesky(G.astype(np.float64)).T
    out = []
    x = np.zeros(n, dtype=np.int64)

    def rec(k: int, partial: np.ndarray, rem: float):
        if k < 0:
            nrm = int(x @ G @ x)
            if 0 < nrm <= bound:
                out.append((nrm, x.copy()))
            return
        rkk = R[k, k]
        centre = -partial[k] / rkk
        half = (max(rem, 0.0) ** 0.5) / rkk + 1e-6
        for xv in range(int(np.ceil(centre - half)), int(np.floor(centre + half)) + 1):
            x[k] = xv
            t = rkk * xv + partial[k]
            rem2 = rem - t * t
            if rem2 < -0.5:
                x[k] = 0
                continue
            rec(k - 1, partial + R[:, k] * xv, max(rem2, 0.0))
        x[k] = 0

    rec(n - 1, np.zeros(n), float(bound) + 0.9)
    return out


def s2e_genS_is_pairsum(S, IB8, pairlats):
    """<S>_Z = Fix(t1) + Fix(t2) + Fix(t3) (the sum of the three BW16 pair
    lattices)?  Compare HNFs."""
    t0 = time.time()
    HS, idxS = lattice_hnf(coords_of(S, IB8))
    HP, idxP = lattice_hnf(coords_of(np.concatenate(pairlats, axis=0), IB8))
    result("S2e", genS_equals_sum_of_pair_lattices=bool(HS == HP and idxS == idxP),
           index_both=idxS, seconds=round(time.time() - t0, 1))


def s4d_channels(blocks, IB8, types, cross_masks):
    """Glue channels: norm-64 vectors of each block classified mod 2Lambda.
    A duad orbit on pair {j,k} is a pair (u, w), u in B_j, w in B_k, norm 64,
    with u = w mod 2Lambda; the common class is the orbit's 'channel'."""
    t0 = time.time()
    pw = (1 << np.arange(24, dtype=np.int64))
    block_classes = []
    frames_orthogonal = True
    for i, Kb in enumerate(blocks):
        vecs = short_vectors_list(Kb @ Kb.T, 64)
        v64 = np.array([c for nrm, c in vecs if nrm == 64]) @ Kb
        assert len(v64) == 2160
        C = coords_of(v64, IB8) % 2
        masks = (C * pw).sum(axis=1)
        cnt = Counter(int(m) for m in masks)
        # each class holds an even number of vectors (+-v same class)
        pairs = {m: c // 2 for m, c in cnt.items()}
        block_classes.append(pairs)
        # each class = a frame of 8 mutually orthogonal +-pairs (rook rows)
        by_class: dict[int, list] = {}
        for m, v in zip(masks, v64):
            by_class.setdefault(int(m), []).append(v)
        for m, vs in by_class.items():
            vs = np.array(vs)
            gg = vs @ vs.T
            if not np.all(np.isin(gg, [0, 64, -64])):
                frames_orthogonal = False
        result("S4d", block=i + 1, norm64_vectors=2160, distinct_classes=len(pairs),
               pairs_per_class=str(dict(Counter(pairs.values()))),
               classes_are_orthogonal_frames=frames_orthogonal)
    # shared channels per block pair and availability
    avail = {}
    shared_sets = {}
    for t, (j, k) in enumerate([(1, 2), (0, 2), (0, 1)]):
        shared = set(block_classes[j]) & set(block_classes[k])
        total = sum(block_classes[j][c] * block_classes[k][c] for c in shared)
        avail[t] = (len(shared), total)
        shared_sets[t] = shared
        result("S4e", pair=f"B{j+1}+B{k+1}", shared_channels=len(shared),
               available_orbits=total, available_duads=4 * total)
    inter3 = shared_sets[0] & shared_sets[1] & shared_sets[2]
    union3 = shared_sets[0] | shared_sets[1] | shared_sets[2]
    rank_u = gf2_rank(sorted(union3))
    with0 = union3 | {0}
    closed = all((x ^ y) in with0 for x in with0 for y in with0)
    result("S4e2", channels_common_to_all_pairs=len(inter3),
           channels_union=len(union3), union_gf2_rank=rank_u,
           union_closed_under_xor=closed,
           union_is_subspace_minus_0=bool(closed and len(union3) == 2 ** rank_u - 1),
           pair_sets_identical=bool(shared_sets[0] == shared_sets[1] == shared_sets[2]))
    # S usage per (pair, channel)
    usage = Counter((t, m) for t, m in zip(types, cross_masks))
    per_pair_channels = {t: sorted(v for (tt, v) in usage if tt == t) for t in range(3)}
    use_hist = {t: sorted(usage[(t, c)] for c in set(per_pair_channels[t]))
                for t in range(3)}
    result("S4f", S_channels_used=str({t: len(set(per_pair_channels[t])) for t in range(3)}),
           S_usage_per_channel=str(use_hist))
    # the 4-dim span of the S-channels: which elements are unused?
    span = gf2_span(sorted(set(cross_masks)))
    words = [0]
    for bvec in span:
        words = words + [w ^ bvec for w in words]
    unused = [w for w in words if w and w not in set(cross_masks)]
    # are the unused elements channels at all (classes of block norm-64 vectors)?
    all_ch = set().union(*[set(bc) for bc in block_classes])
    result("S4g", cross_span_size=len(words), crosses_used=len(set(cross_masks)),
           span_elements_unused=len(unused),
           unused_are_valid_channels=str([w in all_ch for w in unused]),
           seconds=round(time.time() - t0, 1))
    with open(os.path.join(RUNS, "channels.json"), "w") as f:
        json.dump({"blocks": [{str(k): v for k, v in bc.items()} for bc in block_classes],
                   "usage": {f"{t},{m}": c for (t, m), c in usage.items()}}, f, indent=1)
    return block_classes, sorted(union3)


def s4i_channel_geometry(types, cross_masks, T):
    """The 15 channels as points of PG(3,2): subspace structure of the used /
    full / half channel sets per pair."""
    assert len(T) == 15
    usage = Counter((t, m) for t, m in zip(types, cross_masks))
    table = {m: [usage.get((t, m), 0) for t in range(3)] for m in T}

    def closed(sub):
        s = set(sub) | {0}
        return all((x ^ y) in s for x in s for y in s)

    glob_unused = [m for m in T if sum(table[m]) == 0]
    for t in range(3):
        used = [m for m in T if table[m][t] > 0]
        unused = [m for m in T if table[m][t] == 0]
        fullc = [m for m in T if table[m][t] == 8]
        halfc = [m for m in T if table[m][t] == 4]
        result("S4i", pair=t, channels_used=len(used), full=len(fullc), half=len(halfc),
               unused_is_subspace=closed(unused), used_is_subspace=closed(used),
               half_is_subspace=closed(halfc), full_is_subspace=closed(fullc),
               half_rank=gf2_rank(halfc), full_rank=gf2_rank(fullc),
               unused_rank=gf2_rank(unused))
    per_channel_totals = Counter(sum(table[m]) for m in T)
    result("S4i", globally_unused_channels=len(glob_unused),
           per_channel_orbit_totals=str(dict(sorted(per_channel_totals.items()))))
    with open(os.path.join(RUNS, "channel_table.json"), "w") as f:
        json.dump({str(m): table[m] for m in T}, f, indent=1)
    return table


def s4h_rook(sum_vecs, types, cross_masks, ts):
    """Within a channel the 64 orbits form an 8x8 rook grid (rows = u-pairs of
    one block, cols = w-pairs of the other; sharing a row or column forces a
    dot-16 conflict since +-64/4 = +-16 appears among the sign choices).
    Verify S's orbits form partial permutation matrices in every channel."""
    t0 = time.time()
    groups: dict[tuple, list[int]] = {}
    for oi, (t, c) in enumerate(zip(types, cross_masks)):
        groups.setdefault((t, c), []).append(oi)
    ok = True
    full = half = 0
    for (t, c), ois in groups.items():
        rows_by_block: dict[int, set] = {}
        for oi in ois:
            for w in (sum_vecs[2 * oi], sum_vecs[2 * oi + 1]):
                bi = next(i for i, M in enumerate(ts)
                          if np.array_equal((w @ M.T) // 8, -w))
                rows_by_block.setdefault(bi, set()).add(apair_key(w))
        assert len(rows_by_block) == 2
        for bi, keys in rows_by_block.items():
            if len(keys) != len(ois):
                ok = False
        if len(ois) == 8:
            full += 1
        elif len(ois) == 4:
            half += 1
    # channel-level: orbits of one channel across ALL pairs form a matching in
    # K_{8,8,8} (rows = the 8 +-pairs of the channel's frame in each block;
    # two orbits sharing a row conflict at dot 16 by exact arithmetic)
    ch_groups: dict[int, list[int]] = {}
    for oi, c in enumerate(cross_masks):
        ch_groups.setdefault(c, []).append(oi)
    matching_ok = True
    perfect = 0
    totals = Counter()
    for c, ois in ch_groups.items():
        rows_by_block: dict[int, list] = {}
        for oi in ois:
            for w in (sum_vecs[2 * oi], sum_vecs[2 * oi + 1]):
                bi = next(i for i, M in enumerate(ts)
                          if np.array_equal((w @ M.T) // 8, -w))
                rows_by_block.setdefault(bi, []).append(apair_key(w))
        for bi, keys in rows_by_block.items():
            if len(keys) != len(set(keys)):
                matching_ok = False
        totals[len(ois)] += 1
        if len(ois) == 12:
            assert sorted(len(set(v)) for v in rows_by_block.values()) == [8, 8, 8]
            perfect += 1
    result("S4h", cells_full_permutation=full, cells_half=half,
           usage_is_partial_permutation_in_every_cell=ok,
           channel_orbit_totals=str(dict(sorted(totals.items()))),
           channelwise_K888_matching=matching_ok,
           frame_channels_are_perfect_matchings=perfect,
           note="124 = 3 frame channels x 12 (perfect matchings of K888) "
                "+ 9 channels x 8 (one-pair permutations) + 2 channels x (4+4)",
           seconds=round(time.time() - t0, 1))


def s3d_pair_graph(S, V, tup, smask):
    """The single-pair duad graph: 3840 duads on pair {B2,B3} (t1-fixed),
    conflict = dot 16.  Degree structure, spectral (Hoffman) bound (float,
    labelled non-rigorous), and maximality of S's 208 within the pair."""
    t0 = time.time()
    sel = (tup[:, 0] == 0) & (tup[:, 1] == 16) & (tup[:, 2] == 16)
    D1 = V[sel]
    assert len(D1) == 3840
    in_S = smask[sel]
    assert int(in_S.sum()) == 208
    G = D1.astype(np.float64) @ D1.astype(np.float64).T
    A = (G == 16).astype(np.float64)
    deg = A.sum(axis=1)
    degs = sorted(set(int(d) for d in deg))
    hoffman = None
    if len(degs) == 1:
        d = degs[0]
        ev = np.linalg.eigvalsh(A)
        lmin = float(ev[0])
        hoffman = 3840 * (-lmin) / (d - lmin)
    # maximality of the 208 within the pair (exclude +-S members themselves)
    SD = D1[in_S].astype(np.float64)
    conf = ((D1.astype(np.float64) @ SD.T) == 16).sum(axis=1)
    skey = {apair_key(v) for v in D1[in_S]}
    outside = np.array([apair_key(v) not in skey for v in D1])
    min_conf_outside = int(conf[outside].min())
    result("S3d", pair_duads=3840, S_on_pair=208, degrees=str(degs),
           hoffman_bound_float=(round(hoffman, 2) if hoffman else "n/a (irregular)"),
           min_conflicts_outside_pairS=min_conf_outside,
           S208_maximal_within_pair=bool(min_conf_outside > 0),
           seconds=round(time.time() - t0, 1))


def s4c_block_usage(sum_vecs, types, ts):
    """Which norm-64 block vectors the 124 orbits use, per block."""
    t0 = time.time()
    # block of a sum vector = the unique t_i negating it
    per_block: dict[int, set] = {0: set(), 1: set(), 2: set()}
    per_block_orbits: dict[int, int] = {0: 0, 1: 0, 2: 0}
    for w in sum_vecs:
        negs = [i for i, M in enumerate(ts) if np.array_equal((w @ M.T) // 8, -w)]
        assert len(negs) == 1
        per_block[negs[0]].add(apair_key(w))
        per_block_orbits[negs[0]] += 1
    result("S4c", sum_vector_pairs_used_per_block=str({f"B{b+1}": len(v) for b, v in per_block.items()}),
           sum_vectors_per_block=str({f"B{b+1}": per_block_orbits[b] for b in per_block}),
           available_pairs_per_block="1080 (=2160/2 norm-64 vectors of sqrt2E8)",
           seconds=round(time.time() - t0, 1))


def s6_frames(S, class_reps, orbs, types):
    t0 = time.time()
    n = len(class_reps)
    G = class_reps @ class_reps.T
    adj = []
    for i in range(n):
        m = 0
        for j in range(n):
            if i != j and G[i, j] == 0:
                m |= 1 << j
        adj.append(m)

    cliques = []

    def bk(R, P, X):
        if P == 0 and X == 0:
            cliques.append(R)
            return
        PX = P | X
        best, bestc = -1, -1
        m = PX
        while m:
            v = (m & -m).bit_length() - 1
            m &= m - 1
            c = bin(P & adj[v]).count("1")
            if c > bestc:
                bestc, best = c, v
        cand = P & ~adj[best]
        m = cand
        while m:
            v = (m & -m).bit_length() - 1
            m &= m - 1
            bk(R | (1 << v), P & adj[v], X & adj[v])
            P &= ~(1 << v)
            X |= 1 << v

    sys.setrecursionlimit(10000)
    bk(0, (1 << n) - 1, 0)
    sizes = Counter(bin(c).count("1") for c in cliques)
    frames = [c for c in cliques if bin(c).count("1") == 24]
    all_disjoint = all(f1 & f2 == 0 for f1, f2 in combinations(frames, 2))
    frames_idx = [[i for i in range(n) if f >> i & 1] for f in frames]
    covered = set().union(*[set(fi) for fi in frames_idx]) if frames_idx else set()
    result("S6a", maximal_cliques=len(cliques), size_hist=str(dict(sorted(sizes.items()))),
           full_frames=len(frames), pairwise_disjoint=all_disjoint,
           classes_covered=len(covered))

    for fi, fidx in enumerate(frames_idx):
        masks = []
        fset = set(fidx)
        for c in range(n):
            if c in fset:
                continue
            mm = 0
            for pos, j in enumerate(fidx):
                if G[c, j] == 0:
                    mm |= 1 << pos
            assert bin(mm).count("1") == 8
            masks.append(mm)
        distinct = len(set(masks))
        basis = gf2_span(masks)
        dim = len(basis)
        wd = None
        is_golay = False
        if dim <= 13:
            words = [0]
            for bvec in basis:
                words = words + [w ^ bvec for w in words]
            wd = Counter(bin(w).count("1") for w in words)
            is_golay = dict(wd) == {0: 1, 8: 759, 12: 2576, 16: 759, 24: 1}
        result("S6b", frame=fi, external_classes=len(masks), distinct_octads=distinct,
               span_dim=dim, span_weight_dist=str(dict(sorted(wd.items())) if wd else None),
               span_is_golay=is_golay)

    # frame classes by orbit type (block support)
    class_of = {apair_key(r): i for i, r in enumerate(class_reps)}
    type_of_class = {}
    for o, t in zip(orbs, types):
        for j in o:
            type_of_class[class_of[apair_key(S[j])]] = t
    for fi, fidx in enumerate(frames_idx):
        cnt = Counter(type_of_class[c] for c in fidx)
        result("S6c", frame=fi,
               classes_by_support=str({"{B2,B3}": cnt.get(0, 0), "{B1,B3}": cnt.get(1, 0), "{B1,B2}": cnt.get(2, 0)}))
    result("S6", seconds=round(time.time() - t0, 1))
    return frames_idx


def s7_pm16(S, V):
    t0 = time.time()
    Vf = V.astype(np.float64)
    Sf = S.astype(np.float64)
    t_plus = np.zeros(len(V), dtype=np.int64)
    t_minus = np.zeros(len(V), dtype=np.int64)
    step = 16384
    for lo in range(0, len(V), step):
        D = Vf[lo:lo + step] @ Sf.T
        t_plus[lo:lo + step] = (D == 16).sum(axis=1)
        t_minus[lo:lo + step] = (D == -16).sum(axis=1)
    assert np.array_equal(t_plus, t_minus)
    sset = {bytes(r.astype(np.int8)) for r in S}
    smask = np.fromiter((bytes(r) in sset for r in V.astype(np.int8)), dtype=bool, count=len(V))
    outside = ~smask
    th = t_plus[outside]
    hist = Counter(th.tolist())
    assert np.all(t_plus[smask] == 0)
    min_t = int(th.min())
    exp_hist = {4: 80, 6: 640, 7: 256, 8: 2704, 9: 8064, 10: 31424, 11: 52672, 12: 49552,
                13: 31360, 14: 13440, 15: 2560, 16: 1480, 17: 256, 18: 704, 19: 64,
                20: 528, 22: 128, 24: 152}
    assert dict(hist) == exp_hist, dict(hist)
    t4 = V[(t_plus == 4) & outside]
    result("S7a", tightness_hist_outside="matches T3.1 exactly", min_tightness_outside=min_t,
           t4_count=len(t4), plus16_equals_minus16_tightness=True,
           S_maximal_pm16free=bool(min_t > 0),
           union_min_degree_outside=2 * min_t)

    d16 = int(np.sum((Vf[0:1] @ Vf.T) == 16))
    dm16 = int(np.sum((Vf[0:1] @ Vf.T) == -16))
    result("S7b", degree_plus16=d16, degree_minus16=dm16, union_degree=d16 + dm16)

    from bounds.lp_scheme import make_lp, solve_scheme_lp
    from bounds.scheme import load_scheme, eigenmatrices
    eig = eigenmatrices(load_scheme())
    res = solve_scheme_lp(make_lp(eig, forbidden=(1, 5), name="pm16free"))
    res_ap = solve_scheme_lp(make_lp(eig, forbidden=(1, 5), fixed_extra={0: 1},
                                     name="pm16free_antipodal"))
    result("S7c", lp_pm16free_exact=str(res.exact_value), lp_pm16free_floor=res.floor,
           lp_pm16free_antipodal=str(res_ap.exact_value),
           lp_pm16free_antipodal_floor=res_ap.floor,
           lp_conflict_only_T22="9360/11 (=850.9)",
           seconds=round(time.time() - t0, 1))
    return t4


def s8_numerology():
    co0_order = 2 ** 22 * 3 ** 9 * 5 ** 4 * 7 ** 2 * 11 * 13 * 23
    result("S8", co0_order=co0_order, order_div_by_31=bool(co0_order % 31 == 0),
           note="496=2^4*31 (perfect number) and 248=dim(E8 Lie algebra): "
                "31 does not divide |Co0|; no 31-fold symmetry can exist; numerology rejected")


def main():
    t_start = time.time()
    S = load_S()
    V = np.asarray(leech_min_vectors(), dtype=np.int64)
    vindex = {bytes(r): i for i, r in enumerate(V.astype(np.int8))}

    s0_basic(S, V, vindex)
    t1, t2, t3 = s1_stabiliser(S, V, vindex)
    ts = [t1, t2, t3]
    B, IB8 = build_basis(V)
    blocks, pairlats, Ps = s2_blocks(S, V, B, IB8, ts)
    tup, smask, pattern_hist, s_hist = s3_patterns(S, V, ts)
    s3e_family(ts)
    orbs, types, cross_masks, sum_vecs, s_classes = s4_mod2(S, V, IB8, ts)

    # deterministic class representatives (one per antipodal pair)
    seen = {}
    reps = []
    for r in S:
        kcanon = apair_key(r)
        if kcanon not in seen:
            seen[kcanon] = len(reps)
            reps.append(r if tuple(r) > tuple(-r) else -r)
    class_reps = np.array(reps, dtype=np.int64)
    assert class_reps.shape == (248, 24)

    frames_idx = s6_frames(S, class_reps, orbs, types)
    t4 = s7_pm16(S, V)
    s5_sublattices(S, IB8, frames_idx, class_reps, t4, sum_vecs)
    s5b_min_vectors_of_gen(S, V, IB8, tup, smask, t4)
    s4c_block_usage(sum_vecs, types, ts)
    s2e_genS_is_pairsum(S, IB8, pairlats)
    block_classes, T_channels = s4d_channels(blocks, IB8, types, cross_masks)
    s4h_rook(sum_vecs, types, cross_masks, ts)
    s4i_channel_geometry(types, cross_masks, T_channels)
    s3d_pair_graph(S, V, tup, smask)

    # frame <-> channel profile: each frame is a union of 12 orbits; which
    # (pair, channel) cells do they occupy?
    class_of2 = {apair_key(r): i for i, r in enumerate(class_reps)}
    frame_of_class = {}
    for fi, fidx in enumerate(frames_idx):
        for c in fidx:
            frame_of_class[c] = fi
    for fi in range(len(frames_idx)):
        prof = Counter()
        n_orb = 0
        for o, t, cm in zip(orbs, types, cross_masks):
            cls = {class_of2[apair_key(S[j])] for j in o}
            fr = {frame_of_class.get(c, -1) for c in cls}
            assert len(fr) == 1  # an orbit's two classes are in the same frame (or none)
            if fr == {fi}:
                n_orb += 1
                prof[(t, cm)] += 1
        result("S6e", frame=fi, orbits=n_orb,
               cells=str({f"pair{t}/ch{cm % 997}": v for (t, cm), v in sorted(prof.items())}),
               orbits_per_cell=str(sorted(prof.values())))

    # tightness-4 vertices: block-norm patterns (do they look like S?)
    Vf = t4.astype(np.float64)
    pats = []
    for M in ts:
        img = (Vf @ M.T.astype(np.float64)) / 8.0
        d = np.einsum("ij,ij->i", Vf, img).astype(np.int64)
        pats.append((32 - d) // 2)
    t4_tup = np.stack(pats, axis=1)
    t4_uniq, t4_counts = np.unique(t4_tup, axis=0, return_counts=True)
    result("S7d", t4_patterns=str({str(tuple(int(x) for x in u)): int(c)
                                   for u, c in zip(t4_uniq, t4_counts)}))

    s8_numerology()
    result("A4", ok=1, seconds=round(time.time() - t_start, 1))
    with open(os.path.join(RUNS, "summary.json"), "w") as f:
        json.dump(SUMMARY, f, indent=1)


if __name__ == "__main__":
    main()
