"""M24 as the automorphism group of our Golay code, a sextet, and Conway's xi.

How the generators were found (T4.1, 2026-08-25)
------------------------------------------------
Our Golay code (kiss_ref.golay) is the cyclic (23,12,7) code generated by
g(x) = x^11+x^10+x^6+x^5+x^4+x^2+1, extended by a parity bit in coordinate 23.
The cyclic code is a quadratic-residue code on Z/23, so the natural labelling

    coordinate k  <->  field element k  (k = 0..22),   coordinate 23  <->  infinity

puts it in "QR form" with NO extra coordinate permutation: it was checked
computationally (search over all 22 multiplier labellings k -> a*k) that the
identity labelling makes every one of the maps below permute the 4096
codewords.  PSL(2,23) acts on P^1(F_23) = F_23 u {inf} by

    alpha : x -> x + 1                     (order 23)
    gamma : x -> -1/x                      (order 2; 0 <-> inf)

and the standard extra generator of M24 (Conway, SPLAG ch. 10 / ATLAS) is

    delta : x -> x^3 / 9  for x a quadratic residue (incl. 0),
            x -> 9 x^3    for x a non-residue,      inf fixed   (order 5).

The variant with the roles of residues and non-residues swapped does NOT
preserve our code (it preserves the equivalent code on the multiplier
labellings k -> a*k with a a non-residue); this is asserted in the tests.
<alpha, gamma> has order 6072 = |PSL(2,23)|; <alpha, gamma, delta> has order
244,823,040 = |M24| (sympy Schreier-Sims).  The only proof that matters is
that each generator permutes the codeword set; ``preserves_code`` checks it.

Sextet and xi
-------------
``find_sextet`` builds the sextet through a tetrad T (default {0,1,2,3}): for
each point p outside T the unique octad containing T u {p} gives another
tetrad.  Conway's xi acts on each tetrad by the block (1/2)(J - 2I), i.e.
x_i -> (sum over the tetrad)/2 - x_i, with a sign twist: the block is negated
on an ODD number of tetrads (we negate it on the first).  ``verify_aut`` was
used to test all 2^5 sign patterns (up to global sign): the uniform pattern
maps only 49104 of the 196560 minimal vectors back into the set, every
odd-negation pattern is a bijection of the minimal vectors.
"""

from __future__ import annotations

import os
import sys
from itertools import combinations
from typing import Callable, Iterable, Sequence

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from kiss_ref.golay import golay_codewords, octads  # noqa: E402

__all__ = [
    "P",
    "M24_ORDER",
    "PSL_ORDER",
    "QUADRATIC_RESIDUES",
    "permute_mask",
    "preserves_code",
    "psl_generators",
    "delta",
    "m24_generators",
    "group_order",
    "find_sextet",
    "xi_numerators",
    "XI_TETRAD_SIGNS",
    "verify_aut",
    "write_generators",
    "write_xi",
]

P = 23
M24_ORDER = 244_823_040
PSL_ORDER = 6072
INF = None  # the point at infinity of P^1(F_23), coordinate 23

QUADRATIC_RESIDUES = frozenset((x * x) % P for x in range(1, P))
_INV = {x: pow(x, P - 2, P) for x in range(1, P)}


def _coord_to_point(i: int):
    return INF if i == 23 else i


def _point_to_coord(x) -> int:
    return 23 if x is INF else x % P


def _perm_from_map(f: Callable) -> list[int]:
    """perm[i] = image of coordinate i under the map f on P^1(F_23)."""
    perm = [_point_to_coord(f(_coord_to_point(i))) for i in range(24)]
    assert sorted(perm) == list(range(24)), "not a permutation"
    return perm


def permute_mask(mask: int, perm: Sequence[int]) -> int:
    """Move bit i of ``mask`` to position perm[i]."""
    out = 0
    for i in range(24):
        if (mask >> i) & 1:
            out |= 1 << perm[i]
    return out


def preserves_code(perm: Sequence[int], words: Iterable[int] | None = None) -> bool:
    """True iff the coordinate permutation maps every codeword to a codeword."""
    words = list(golay_codewords() if words is None else words)
    s = set(words)
    return all(permute_mask(w, perm) in s for w in words)


def _alpha(x):
    return INF if x is INF else (x + 1) % P


def _gamma(x):
    if x is INF:
        return 0
    if x == 0:
        return INF
    return (-_INV[x]) % P


def psl_generators() -> tuple[list[int], list[int]]:
    """(alpha, gamma) = (x -> x+1, x -> -1/x) as coordinate permutations."""
    return _perm_from_map(_alpha), _perm_from_map(_gamma)


def delta(swap: bool = False) -> list[int]:
    """x -> x^3/9 on residues (and 0), 9x^3 on non-residues, inf fixed.

    ``swap=True`` exchanges the two rules; that variant does not preserve our
    code and is only exposed so the tests can assert it.
    """

    def f(x):
        if x is INF:
            return INF
        if x == 0:
            return 0
        c = pow(x, 3, P)
        is_q = x in QUADRATIC_RESIDUES
        if swap:
            is_q = not is_q
        return (c * _INV[9]) % P if is_q else (9 * c) % P

    return _perm_from_map(f)


def m24_generators() -> list[list[int]]:
    """[alpha, gamma, delta] — verified generators of M24 = Aut(G24)."""
    a, g = psl_generators()
    return [a, g, delta()]


def group_order(gens: Sequence[Sequence[int]]) -> int:
    """Order of the permutation group generated by ``gens`` (sympy Schreier-Sims)."""
    from sympy.combinatorics import Permutation, PermutationGroup

    return int(PermutationGroup([Permutation(list(g)) for g in gens]).order())


# ---------------------------------------------------------------------------
# Sextet and xi
# ---------------------------------------------------------------------------


def _bits(mask: int) -> list[int]:
    return [i for i in range(24) if (mask >> i) & 1]


def find_sextet(tetrad: Sequence[int] = (0, 1, 2, 3)) -> list[list[int]]:
    """The sextet containing ``tetrad``: 6 tetrads, any two forming an octad."""
    t0 = sorted(int(i) for i in tetrad)
    assert len(t0) == 4 and all(0 <= i < 24 for i in t0)
    octs = octads()
    m0 = sum(1 << i for i in t0)
    tetrads = [t0]
    used = set(t0)
    while len(used) < 24:
        p = min(set(range(24)) - used)
        m = m0 | (1 << p)
        oc = [o for o in octs if (o & m) == m]
        assert len(oc) == 1, "S(5,8,24): T u {p} lies in exactly one octad"
        t = [i for i in _bits(oc[0]) if i not in used and i not in t0]
        assert len(t) == 4
        tetrads.append(t)
        used |= set(t)
    oset = set(octs)
    for a, b in combinations(tetrads, 2):
        assert sum(1 << i for i in a + b) in oset
    return tetrads


#: Sign of the (1/2)(J - 2I) block on each tetrad of the chosen xi.
XI_TETRAD_SIGNS = (-1, 1, 1, 1, 1, 1)


def xi_numerators(sextet: Sequence[Sequence[int]], signs: Sequence[int] = XI_TETRAD_SIGNS) -> list[list[int]]:
    """24x24 integer numerators of xi over the common denominator 2.

    Row r, column c: (xi v)[r] = sum_c num[r][c] v[c] / 2.  On tetrad T with
    sign s the block is s * (J - 2I), i.e. s for r != c in T, -s for r == c.
    """
    num = [[0] * 24 for _ in range(24)]
    for t, s in zip(sextet, signs):
        for r in t:
            for c in t:
                num[r][c] = int(s) * (-1 if r == c else 1)
    return num


def verify_aut(num: Sequence[Sequence[int]], den: int) -> tuple[int, bool]:
    """Apply (num/den) to all 196560 minimal vectors.

    Returns (number of images that are minimal vectors, bijection?).  An image
    with a non-integer coordinate counts as "not in C".
    """
    import numpy as np

    from kiss_ref.leech import leech_min_vectors

    C8 = leech_min_vectors()
    C = C8.astype(np.int64)
    M = np.asarray(num, dtype=np.int64)
    img = C @ M.T
    ok_int = np.all(img % den == 0, axis=1)
    img = img // den
    keys = np.ascontiguousarray(C8).view(np.dtype((np.void, 24))).ravel()
    order = np.argsort(keys)
    sk = keys[order]
    small = np.all(np.abs(img) <= 127, axis=1)
    img8 = np.clip(img, -127, 127).astype(np.int8)
    k = np.ascontiguousarray(img8).view(np.dtype((np.void, 24))).ravel()
    pos = np.minimum(np.searchsorted(sk, k), len(sk) - 1)
    hit = (sk[pos] == k) & ok_int & small
    idx = np.where(hit, order[pos], -1)
    n_in = int(hit.sum())
    bij = n_in == len(C) and len(np.unique(idx)) == len(C)
    return n_in, bij


# ---------------------------------------------------------------------------
# Data files (data/group/)
# ---------------------------------------------------------------------------


def write_generators(path: str) -> None:
    gens = m24_generators()
    names = ["alpha: x -> x+1", "gamma: x -> -1/x", "delta: x -> x^3/9 (Q), 9x^3 (N)"]
    with open(path, "w") as f:
        f.write("# M24 generators as coordinate permutations of our Golay code (bit i = coordinate i).\n")
        f.write("# One permutation per line: images of coordinates 0..23.  Coordinate k <-> k in F_23, 23 <-> inf.\n")
        f.write("# Generated by python/group/m24.py; each line verified to permute the 4096 codewords;\n")
        f.write("# <alpha,gamma> has order 6072 = |PSL(2,23)|, <alpha,gamma,delta> has order 244823040 = |M24|.\n")
        for name, g in zip(names, gens):
            assert preserves_code(g)
            f.write(" ".join(str(v) for v in g) + f"   # {name}\n")


def write_xi(path: str, sextet_path: str | None = None) -> None:
    sextet = find_sextet()
    num = xi_numerators(sextet)
    n_in, bij = verify_aut(num, 2)
    assert n_in == 196560 and bij, (n_in, bij)
    with open(path, "w") as f:
        f.write("# Conway's xi for the sextet below: on tetrad T, x_i -> s_T * ((sum_{j in T} x_j)/2 - x_i).\n")
        f.write("# sextet: " + " | ".join(" ".join(str(i) for i in t) for t in sextet) + "\n")
        f.write("# tetrad signs s_T: " + " ".join(str(s) for s in XI_TETRAD_SIGNS) + "\n")
        f.write("# Verified (python/group/m24.py): maps all 196560 minimal vectors bijectively onto themselves.\n")
        f.write("# Format: 'den D' then 24 rows of 24 integer numerators; (xi v)[r] = sum_c num[r][c] v[c] / D.\n")
        f.write("den 2\n")
        for row in num:
            f.write(" ".join(f"{v:2d}" for v in row) + "\n")
    if sextet_path:
        with open(sextet_path, "w") as f:
            f.write("# Sextet of our Golay code through the tetrad {0,1,2,3}: one tetrad per line;\n")
            f.write("# the union of any two tetrads is an octad.\n")
            for t in sextet:
                f.write(" ".join(str(i) for i in t) + "\n")


def main(argv: Sequence[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "..", "data", "group"))
    args = ap.parse_args(argv)
    os.makedirs(args.out, exist_ok=True)
    gens = m24_generators()
    for g in gens:
        assert preserves_code(g)
    order = group_order(gens)
    assert order == M24_ORDER, order
    write_generators(os.path.join(args.out, "m24_generators.txt"))
    write_xi(os.path.join(args.out, "xi.txt"), os.path.join(args.out, "sextet.txt"))
    print(f"RESULT ok=1 m24_order={order} psl_order={group_order(list(psl_generators()))} out={args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
