// T1.1 — extended binary Golay code G24 (docs/design.md §2.3, README §1.2).
//
// Construction: the cyclic (23,12,7) Golay code generated by
//   g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1
// (every codeword is m(x)·g(x) over GF(2) with deg m <= 11), extended by an
// overall parity bit to length 24.
//
// Coordinate convention (fixed by docs/design.md §2.2 / T1.1): a codeword is a 24-bit
// mask in a uint32_t; bit i (value 1u << i) is coordinate i and holds the
// coefficient of x^i for i = 0..22; bit 23 is the parity coordinate.
#pragma once

#include <array>
#include <cstdint>
#include <vector>

namespace kiss {

// Generator polynomial g(x) as a bit mask (bit i = coefficient of x^i).
constexpr uint32_t GOLAY_GENERATOR = 0xC75u;  // x^11+x^10+x^6+x^5+x^4+x^2+1

// All 4096 codewords of G24 as 24-bit masks, sorted ascending.
// Computed once and cached; the returned vector is a copy of the cache.
std::vector<uint32_t> golay_codewords();

// weight → count over the given words (index = popcount, 0..24).
std::array<int, 25> golay_weight_distribution(const std::vector<uint32_t>& words);

// Membership test: true iff mask is one of the 4096 codewords.
// Masks with bits above 23 set are never codewords. O(1) via a cached
// 2^24-bit table (2 MiB), built on first use.
bool golay_is_codeword(uint32_t mask);

// The 759 weight-8 codewords (octads, blocks of the Steiner system S(5,8,24)),
// sorted ascending.
std::vector<uint32_t> golay_octads();

}  // namespace kiss
