// T3.4 — symmetry-restricted search: orbits of a subgroup H ≤ Co_0 on the
// 196560 minimal vectors, the weighted orbit-conflict graph, and maximum
// weight independent sets of orbits (README §3 W2d, docs/design.md T3.4).
//
// An H-invariant independent set of the conflict graph is a union of
// H-orbits none of which is self-conflicting (contains a 60° pair) and no two
// of which conflict (some cross pair at 60°). Because the orbits are
// H-invariant, one representative per orbit sees every conflicting orbit:
// for r ∈ A the orbit ids hit by row(r) of the adjacency table are exactly the
// orbits conflicting with A (A itself included iff A is self-conflicting).
//
// Builds on kiss/group.h (IndexPerm) and kiss/adjacency.h (data/adj.u32).
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "kiss/adjacency.h"
#include "kiss/group.h"
#include "kiss/types.h"

namespace kiss {

// A subgroup given by generators (index permutations of C).
struct Subgroup {
  std::vector<IndexPerm> gens;
  std::string name;
};

// Orbit decomposition of {0..N-1} under the group generated by `gens`.
struct Orbits {
  std::vector<uint32_t> id;       // id[v] = orbit of vertex v (0..count()-1)
  std::vector<uint32_t> start;    // CSR offsets into members, size count()+1
  std::vector<uint32_t> members;  // vertices grouped by orbit, size N; orbit o = members[start[o] .. start[o+1])
  uint32_t count() const { return static_cast<uint32_t>(start.size() - 1); }
  uint32_t size(uint32_t o) const { return start[o + 1] - start[o]; }
  uint32_t rep(uint32_t o) const { return members[start[o]]; }  // smallest vertex of the orbit
};

// Union-find over all generators, O(N·|gens|). Orbits are numbered in order of
// their smallest vertex. An empty generator list gives N singleton orbits.
Orbits orbits(const Subgroup& H);
// True iff every orbit is mapped onto itself by g (id[g[v]] == id[v] ∀v).
bool orbits_invariant(const Orbits& O, const IndexPerm& g);
// If S_idx (vertex indices) is a union of orbits, return true and fill
// `orbit_ids` (sorted, unique); else false (orbit_ids then holds the
// partially covered orbits).
bool is_orbit_union(const Orbits& O, const std::vector<uint32_t>& S_idx, std::vector<uint32_t>& orbit_ids);
// Vertices of the given orbits (sorted ascending).
std::vector<uint32_t> union_of_orbits(const Orbits& O, const std::vector<uint32_t>& orbit_ids);

// Orbit conflict graph. Vertex o has weight |orbit o|. Self-conflicting
// orbits can never be chosen; they are kept as vertices (so ids match the
// Orbits) but have no adjacency list and are skipped by all solvers.
// If count() ≤ max_explicit the neighbour lists are stored (CSR, both
// directions, self loops excluded); otherwise they are recomputed on demand
// from the representative's adjacency row (implicit mode).
class OrbitGraph {
 public:
  OrbitGraph(const Orbits& O, const Adjacency& A, uint32_t max_explicit = 20000);
  // Synthetic explicit graph (for tests): vertex o has weight weights[o],
  // `edges` are unordered pairs (duplicates / both orientations allowed,
  // self loops mark the vertex self-conflicting), `self` optional flags.
  // orbits() must not be called on such a graph.
  OrbitGraph(const std::vector<uint32_t>& weights, const std::vector<std::pair<uint32_t, uint32_t>>& edges,
             const std::vector<uint8_t>& self = {});

  uint32_t n() const { return n_; }
  uint32_t weight(uint32_t o) const { return weight_[o]; }
  bool self_conflicting(uint32_t o) const { return self_[o] != 0; }
  uint32_t degree(uint32_t o) const { return degree_[o]; }  // # distinct other orbits conflicting with o
  uint64_t edges() const { return edges_; }                 // unordered pairs of distinct conflicting orbits
  uint32_t self_conflicting_count() const { return n_self_; }
  bool is_explicit() const { return explicit_; }
  const Orbits& orbits() const { return *orb_; }

  // Distinct orbits conflicting with o (o itself excluded), ascending.
  // Explicit mode: a view into the CSR; implicit mode: computed into `buf`.
  const uint32_t* neighbours(uint32_t o, uint32_t& count, std::vector<uint32_t>& buf) const;
  // Brute-force conflict test between two orbits (all cross pairs via dot on
  // the vectors); for tests only.
  static bool conflict_brute_force(const Leech& L, const Orbits& O, uint32_t a, uint32_t b);

 private:
  void neighbours_of_row(uint32_t o, std::vector<uint32_t>& out) const;
  const Orbits* orb_ = nullptr;
  const Adjacency* adj_ = nullptr;
  uint32_t n_ = 0, n_self_ = 0;
  std::vector<uint32_t> weight_;
  uint64_t edges_ = 0;
  bool explicit_ = false;
  std::vector<uint8_t> self_;
  std::vector<uint32_t> degree_;
  std::vector<uint64_t> csr_start_;  // explicit only
  std::vector<uint32_t> csr_;        // explicit only
};

// A set of orbits with its total weight (number of vertices).
struct OrbitSet {
  std::vector<uint32_t> orbits;  // sorted ascending
  uint64_t weight = 0;
  bool optimal = false;   // proven maximum (branch-and-bound finished)
  double seconds = 0;
  uint64_t nodes = 0;     // B&B nodes or local-search iterations
};

// Greedy: orbits by (weight desc, degree asc), take each that is free.
OrbitSet greedy_orbit_mis(const OrbitGraph& G);
// Iterated local search (ARW-style perturbation + free-orbit filling,
// weight-aware) starting from `init`, for `seconds` wall-clock.
OrbitSet local_search_orbit_mis(const OrbitGraph& G, const OrbitSet& init, double seconds, uint64_t seed,
                                uint64_t max_iters = 0);
// Exact branch-and-bound on the explicit orbit graph restricted to the
// non-self-conflicting orbits (bitset adjacency, clique-cover weight bound).
// Starts from lower bound `init` (the result is at least as good). If the
// time limit expires the best set found is returned with optimal = false.
// Throws std::runtime_error if G is not explicit.
OrbitSet branch_and_bound_orbit_mis(const OrbitGraph& G, const OrbitSet& init, double seconds,
                                    uint32_t max_vertices = 20000);
// Verify an OrbitSet is a valid independent union (no self-conflicting orbit,
// no conflicting pair) — by the explicit/implicit neighbour lists.
bool orbit_set_valid(const OrbitGraph& G, const OrbitSet& s);

// ---------------------------------------------------------------------------
// Helpers for building subgroups of the monomial group / Co_0
// ---------------------------------------------------------------------------
// Order of a monomial element (smallest k ≥ 1 with m^k = 1).
int monomial_order(const Monomial& m);
// Order of the group generated by monomial elements by BFS closure; returns
// 0 if it exceeds `cap`.
uint64_t monomial_group_order(const std::vector<Monomial>& gens, uint64_t cap = 5000000);
// Order of an index permutation (lcm of cycle lengths).
uint64_t index_perm_order(const IndexPerm& g);
// Random word in the given monomial generators (uniform letters, length `len`).
Monomial random_monomial_word(const std::vector<Monomial>& gens, int len, std::mt19937_64& rng);
// Parse a "monomial list" file: '#' comments; per line 24 coordinate images
// followed by the sign mask (decimal); an optional trailing '#' comment.
std::vector<Monomial> load_monomial_list(const std::filesystem::path& path);
void save_monomial_list(const std::filesystem::path& path, const std::vector<Monomial>& ms,
                        const std::string& header_comment = "");

}  // namespace kiss
