// triple_orbitals (T2.3): the orbitals of the point stabiliser Stab(x) of the
// group Gamma = <five explicit Co_0 generators of data/group> acting on the
// 196560 Leech minimal vectors, their intersection numbers (the structure
// constants of the centraliser algebra of Stab(x) = the Terwilliger-type
// algebra T(x) the three-point SDP lives in), the S_3 action on them, and the
// triple-orbit counts of given sets (S496, S488) — everything the SDP in
// python/bounds/sdp3_scheme.py needs.  docs/reports/T2.3.md section 1.
//
// Rigour.  Every identification of two ordered triples (x,y,z), (x,y',z') as
// "in the same orbit" made here is witnessed by an explicit group element
// (a product of the generators and their inverses): orbits are computed by
// union-find over explicit permutations, and pairs are labelled by mapping
// them onto a representative with explicit transversal elements (Schreier
// vectors).  So the labels computed here REFINE the true Stab(x)-orbitals
// (they are orbits of subgroups K_i <= Stab(x, y_i) generated by random
// elements).  tools/triple_stats.cpp gives an independent LOWER bound on the
// number of Stab(x)-orbitals (distinct 4-point histograms, a Stab(x,y)-
// invariant); when the two numbers agree (148 = 148) the labels ARE the
// orbitals and their span is the centraliser algebra of Stab(x), an algebra
// closed under transposition.  The Python side makes that comparison.
//
// Steps (x = C[0] by default):
//   1. gens = co0_generator_perms (each verified to map C onto C).
//   2. BFS orbit of x under gens u gens^-1 with a Schreier vector: transversal
//      elements u_v (u_v x = v) for all v; orbit must be all of V (T2.2).
//   3. Random elements of Stab(x): g random (product replacement), h = u_{gx}^-1 g.
//      Orbits of <h_1..h_m> on V; must be the 7 inner-product classes.
//   4. Per class i, y_i = smallest vertex of the class, Schreier vector of the
//      <h>-orbit of y_i (= class i): transversals t_v, t_v y_i = v.
//   5. Per class i, random elements of Stab(x, y_i): k = t_{h y_i}^-1 h; orbits of
//      <k_1..k_m> on V = the labels lab_i[w]; more elements are added until the
//      orbit count is stable for `patience` further elements.
//   6. Orbitals u = (i, o): pairs (y, z) with class(x,y) = i and t_y^-1 z in
//      orbit o of class i's labels; size |u| = v_i |o|; representative (y_i, z_o).
//      orbital_of(a, b) = (class(a), lab_{class(a)}[t_a^-1 b]).
//      transpose(u) = orbital_of(z_o, y_i);  swap_xy(u) = orbital_of(u_{y_i}^-1 x, u_{y_i}^-1 z_o)
//      (the triple (y_i, x, z_o) moved back to base point x).
//   7. Structure constants c[u][s][t] = #{w : (y_i, w) in s, (w, z_o) in t}
//      at the representative of u, and again at a random second representative
//      (must agree).
//   8. --set FILE (repeatable): n_O(S) = #{(x',y',z') in S^3 : orbit O} per orbital
//      (triple (x',y',z') moved to (x, u_{x'}^-1 y', u_{x'}^-1 z')).
//
// Output: data/scheme/orbitals.json (or --out).  Last line: RESULT ok=<0|1> ...
// Usage: triple_orbitals [--data DIR] [--group DIR] [--x IDX] [--out PATH] [--seed S]
//                        [--stab-elements M] [--patience P] [--set PATH]...
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <numeric>
#include <random>
#include <stdexcept>
#include <string>
#include <vector>

#include "kiss/group.h"
#include "kiss/io.h"
#include "kiss/leech.h"
#include "kiss/orbits.h"
#include "kiss/types.h"

using kiss::IndexPerm;
using kiss::Leech;
using kiss::N;

namespace {

constexpr int NC = 7;

struct Timer {
  std::chrono::steady_clock::time_point t0 = std::chrono::steady_clock::now();
  double ms() const { return std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count(); }
};

// A set of "moves" (permutations and their inverses) with a BFS Schreier
// vector rooted at one or several roots.
struct Schreier {
  std::vector<IndexPerm> moves;      // moves[2m] = g_m, moves[2m+1] = g_m^-1
  std::vector<uint32_t> parent;      // parent[v]; parent[root] = root
  std::vector<uint16_t> move;        // v = moves[move[v]](parent[v])
  std::vector<uint8_t> depth_dummy;  // unused
  std::vector<uint8_t> is_root;
  uint32_t max_depth = 0;

  void set_moves(const std::vector<IndexPerm>& gens) {
    moves.clear();
    for (const auto& g : gens) {
      moves.push_back(g);
      moves.push_back(kiss::inverse(g));
    }
  }
  // BFS from every root; returns the number of vertices reached.
  std::size_t bfs(const std::vector<uint32_t>& roots) {
    parent.assign(static_cast<std::size_t>(N), UINT32_MAX);
    move.assign(static_cast<std::size_t>(N), 0);
    is_root.assign(static_cast<std::size_t>(N), 0);
    std::vector<uint32_t> depth(static_cast<std::size_t>(N), 0);
    std::vector<uint32_t> queue;
    queue.reserve(static_cast<std::size_t>(N));
    for (uint32_t r : roots) {
      parent[r] = r;
      is_root[r] = 1;
      queue.push_back(r);
    }
    max_depth = 0;
    for (std::size_t head = 0; head < queue.size(); ++head) {
      const uint32_t v = queue[head];
      for (std::size_t m = 0; m < moves.size(); ++m) {
        const uint32_t w = moves[m][v];
        if (parent[w] == UINT32_MAX) {
          parent[w] = v;
          move[w] = static_cast<uint16_t>(m);
          depth[w] = depth[v] + 1;
          max_depth = std::max(max_depth, depth[w]);
          queue.push_back(w);
        }
      }
    }
    return queue.size();
  }
  // u_v^-1 applied to p, where u_v is the transversal element with u_v(root) = v.
  uint32_t apply_inv(uint32_t v, uint32_t p) const {
    while (!is_root[v]) {
      p = moves[move[v] ^ 1u][p];
      v = parent[v];
    }
    return p;
  }
  // u_v applied to p.
  uint32_t apply(uint32_t v, uint32_t p) const {
    uint16_t path[4096];
    int n = 0;
    while (!is_root[v]) {
      if (n >= 4096) throw std::runtime_error("Schreier path too long");
      path[n++] = move[v];
      v = parent[v];
    }
    for (int q = n - 1; q >= 0; --q) p = moves[path[q]][p];
    return p;
  }
  // Full permutation u_v^-1 composed with g: out[p] = u_v^-1(g[p]).
  void inv_after(uint32_t v, const IndexPerm& g, IndexPerm& out) const {
    out.resize(static_cast<std::size_t>(N));
#pragma omp parallel for schedule(static)
    for (int p = 0; p < N; ++p) out[static_cast<std::size_t>(p)] = apply_inv(v, g[static_cast<std::size_t>(p)]);
  }
};

struct UnionFind {
  std::vector<uint32_t> parent;
  explicit UnionFind(std::size_t n) : parent(n) { std::iota(parent.begin(), parent.end(), 0u); }
  uint32_t find(uint32_t a) {
    while (parent[a] != a) { parent[a] = parent[parent[a]]; a = parent[a]; }
    return a;
  }
  bool unite(uint32_t a, uint32_t b) {
    a = find(a); b = find(b);
    if (a == b) return false;
    if (a < b) parent[b] = a; else parent[a] = b;
    return true;
  }
  // Add a permutation: unite v with g[v].  Returns the number of merges.
  std::size_t add(const IndexPerm& g) {
    std::size_t merges = 0;
    for (uint32_t v = 0; v < static_cast<uint32_t>(N); ++v) merges += unite(v, g[v]);
    return merges;
  }
  // Labels 0..count-1 in order of the smallest member; returns count.
  uint32_t labels(std::vector<uint32_t>& lab) {
    lab.assign(static_cast<std::size_t>(N), UINT32_MAX);
    uint32_t count = 0;
    for (uint32_t v = 0; v < static_cast<uint32_t>(N); ++v) {
      const uint32_t r = find(v);
      if (lab[r] == UINT32_MAX) lab[r] = count++;
      lab[v] = lab[r];
    }
    return count;
  }
};

int cls_of(const Leech& L, uint32_t a, uint32_t b) {
  const int c = kiss::ip_class(kiss::dot(L.C[a], L.C[b]));
  if (c < 0) throw std::runtime_error("inner product outside the classes");
  return c;
}

}  // namespace

int main(int argc, char** argv) {
  std::filesystem::path data_dir = "data", group_dir, out = "data/scheme/orbitals.json";
  uint32_t x = 0;
  uint64_t seed = 20260826ull;
  int stab_elements = 4, patience = 4;
  std::vector<std::filesystem::path> sets;
  for (int i = 1; i < argc; ++i) {
    if (!std::strcmp(argv[i], "--data") && i + 1 < argc) data_dir = argv[++i];
    else if (!std::strcmp(argv[i], "--group") && i + 1 < argc) group_dir = argv[++i];
    else if (!std::strcmp(argv[i], "--out") && i + 1 < argc) out = argv[++i];
    else if (!std::strcmp(argv[i], "--x") && i + 1 < argc) x = static_cast<uint32_t>(std::atoi(argv[++i]));
    else if (!std::strcmp(argv[i], "--seed") && i + 1 < argc) seed = std::strtoull(argv[++i], nullptr, 10);
    else if (!std::strcmp(argv[i], "--stab-elements") && i + 1 < argc) stab_elements = std::max(1, std::atoi(argv[++i]));
    else if (!std::strcmp(argv[i], "--patience") && i + 1 < argc) patience = std::max(1, std::atoi(argv[++i]));
    else if (!std::strcmp(argv[i], "--set") && i + 1 < argc) sets.emplace_back(argv[++i]);
    else { std::fprintf(stderr, "unknown argument %s\n", argv[i]); return 1; }
  }
  if (group_dir.empty()) group_dir = data_dir / "group";
  try {
    Timer total;
    const Leech L = kiss::load_leech(data_dir);
    if (x >= static_cast<uint32_t>(N)) throw std::runtime_error("x out of range");
    std::vector<uint8_t> cls(static_cast<std::size_t>(N));
    std::array<uint32_t, NC> val{};
    std::array<uint32_t, NC> yrep{};
    std::array<bool, NC> have{};
    for (uint32_t v = 0; v < static_cast<uint32_t>(N); ++v) {
      const int c = cls_of(L, x, v);
      cls[v] = static_cast<uint8_t>(c);
      ++val[static_cast<std::size_t>(c)];
      if (!have[static_cast<std::size_t>(c)]) { have[static_cast<std::size_t>(c)] = true; yrep[static_cast<std::size_t>(c)] = v; }
    }
    std::printf("x=%u valencies:", x);
    for (int c = 0; c < NC; ++c) std::printf(" %u", val[static_cast<std::size_t>(c)]);
    std::printf("  class representatives y_i:");
    for (int c = 0; c < NC; ++c) std::printf(" %u", yrep[static_cast<std::size_t>(c)]);
    std::printf("\n");

    // 1-2. generators and the orbit of x with a Schreier vector.
    Timer tg;
    const std::vector<IndexPerm> gens = kiss::co0_generator_perms(L, group_dir);
    Schreier S0;
    S0.set_moves(gens);
    const std::size_t orb = S0.bfs({x});
    std::printf("Gamma = <%zu generators> (data/group, each verified to map C onto C): orbit of x = %zu of %d, "
                "Schreier depth %u (%.0f ms)\n", gens.size(), orb, N, S0.max_depth, tg.ms());
    if (orb != static_cast<std::size_t>(N)) throw std::runtime_error("Gamma is not transitive on C");

    // 3. random elements of Stab(x).
    Timer th;
    kiss::ProductReplacement pr(gens, 10, seed);
    pr.burn_in(200);
    std::vector<IndexPerm> hs;
    auto random_stab_x = [&](IndexPerm& h) {
      const IndexPerm& g = pr.next();
      S0.inv_after(g[x], g, h);
      if (h[x] != x) throw std::runtime_error("random element does not fix x");
    };
    UnionFind ufx(static_cast<std::size_t>(N));
    std::vector<uint32_t> labx;
    uint32_t nx = 0;
    for (int m = 0; m < stab_elements || nx != NC; ++m) {
      if (m > 64) throw std::runtime_error("orbits of the random Stab(x) elements did not reach the 7 classes");
      hs.emplace_back();
      random_stab_x(hs.back());
      ufx.add(hs.back());
      nx = ufx.labels(labx);
    }
    // the orbits must be exactly the classes
    for (uint32_t v = 0; v < static_cast<uint32_t>(N); ++v)
      if (labx[v] != labx[yrep[cls[v]]]) throw std::runtime_error("Stab(x)-orbit is not a class");
    std::printf("Stab(x): %zu random elements, orbits on C = %u = the inner-product classes (%.0f ms)\n", hs.size(), nx, th.ms());

    // 4. Schreier vectors inside each class (all classes at once: the roots are the y_i).
    Schreier S1;
    S1.set_moves(hs);
    {
      std::vector<uint32_t> roots(yrep.begin(), yrep.end());
      const std::size_t reached = S1.bfs(roots);
      if (reached != static_cast<std::size_t>(N)) throw std::runtime_error("class BFS did not reach every vertex");
      std::printf("class transversals: Schreier depth %u\n", S1.max_depth);
    }

    // 5. labels per class: orbits of random elements of Stab(x, y_i).
    std::array<std::vector<uint32_t>, NC> lab;
    std::array<uint32_t, NC> nlab{};
    std::array<int, NC> nk{};
    Timer tk;
    for (int i = 0; i < NC; ++i) {
      const uint32_t yi = yrep[static_cast<std::size_t>(i)];
      UnionFind uf(static_cast<std::size_t>(N));
      IndexPerm h, k(static_cast<std::size_t>(N));
      uint32_t count = static_cast<uint32_t>(N);
      int stable = 0;
      while (stable < patience) {
        random_stab_x(h);
        const uint32_t hy = h[yi];
#pragma omp parallel for schedule(static)
        for (int p = 0; p < N; ++p) k[static_cast<std::size_t>(p)] = S1.apply_inv(hy, h[static_cast<std::size_t>(p)]);
        if (k[x] != x || k[yi] != yi) throw std::runtime_error("random element does not fix (x, y_i)");
        ++nk[static_cast<std::size_t>(i)];
        uf.add(k);
        std::vector<uint32_t> tmp;
        const uint32_t c = uf.labels(tmp);
        if (c == count) ++stable; else { stable = 0; count = c; }
        lab[static_cast<std::size_t>(i)] = std::move(tmp);
        nlab[static_cast<std::size_t>(i)] = c;
        if (nk[static_cast<std::size_t>(i)] > 200) throw std::runtime_error("label count did not stabilise");
      }
      std::printf("  class %d (y_%d = %u): %d random elements of Stab(x, y_i), orbits on C: %u\n", i, i, yi, nk[static_cast<std::size_t>(i)], nlab[static_cast<std::size_t>(i)]);
    }
    uint32_t D = 0;
    for (int i = 0; i < NC; ++i) D += nlab[static_cast<std::size_t>(i)];
    std::printf("orbitals of Stab(x) (labels): D = %u (%.0f ms)\n", D, tk.ms());

    // 6. orbitals
    struct Orbital { int i; uint32_t o; uint32_t z; int j, k; uint64_t size; uint32_t osize; uint32_t transpose = 0, swap_xy = 0; };
    std::vector<Orbital> orbs;
    std::array<std::vector<uint32_t>, NC> id;   // id[i][o] -> global
    for (int i = 0; i < NC; ++i) {
      std::vector<uint32_t> osz(nlab[static_cast<std::size_t>(i)], 0u), zrep(nlab[static_cast<std::size_t>(i)], UINT32_MAX);
      for (uint32_t v = 0; v < static_cast<uint32_t>(N); ++v) {
        const uint32_t o = lab[static_cast<std::size_t>(i)][v];
        ++osz[o];
        if (zrep[o] == UINT32_MAX) zrep[o] = v;   // labels are numbered by smallest member, so this is the smallest
      }
      id[static_cast<std::size_t>(i)].resize(nlab[static_cast<std::size_t>(i)]);
      for (uint32_t o = 0; o < nlab[static_cast<std::size_t>(i)]; ++o) {
        Orbital u;
        u.i = i; u.o = o; u.z = zrep[o]; u.j = cls[zrep[o]]; u.k = cls_of(L, yrep[static_cast<std::size_t>(i)], zrep[o]);
        u.osize = osz[o];
        u.size = static_cast<uint64_t>(val[static_cast<std::size_t>(i)]) * osz[o];
        id[static_cast<std::size_t>(i)][o] = static_cast<uint32_t>(orbs.size());
        orbs.push_back(u);
      }
    }
    auto orbital_of = [&](uint32_t a, uint32_t b) -> uint32_t {
      const int i = cls[a];
      const uint32_t w = S1.apply_inv(a, b);
      return id[static_cast<std::size_t>(i)][lab[static_cast<std::size_t>(i)][w]];
    };
    // sanity: the orbital labels are consistent with the class of the pair (invariant under the group)
    for (auto& u : orbs) {
      const uint32_t yi = yrep[static_cast<std::size_t>(u.i)];
      u.transpose = orbital_of(u.z, yi);
      u.swap_xy = orbital_of(S0.apply_inv(yi, x), S0.apply_inv(yi, u.z));
    }
    long long bad_inv = 0, bad_size = 0, bad_cls = 0;
    for (std::size_t u = 0; u < orbs.size(); ++u) {
      const Orbital& a = orbs[u];
      const Orbital& t = orbs[a.transpose];
      const Orbital& s = orbs[a.swap_xy];
      if (orbs[a.transpose].transpose != u || orbs[a.swap_xy].swap_xy != u) ++bad_inv;
      if (t.size != a.size || s.size != a.size) ++bad_size;
      // transpose: (z, y): class(x,z) = j, class(x,y) = i, class(z,y) = k ; swap: (x,y,z)->(y,x,z): i'=i, j'=k, k'=j
      if (t.i != a.j || t.j != a.i || t.k != a.k) ++bad_cls;
      if (s.i != a.i || s.j != a.k || s.k != a.j) ++bad_cls;
    }
    std::printf("S_3 action on orbitals: transpose/swap involutions bad %lld, size mismatches %lld, class-pattern mismatches %lld\n",
                bad_inv, bad_size, bad_cls);

    // 7. structure constants c[u][s][t]
    Timer tc;
    std::vector<uint32_t> c(static_cast<std::size_t>(D) * D * D, 0u);
    std::vector<uint32_t> c2(static_cast<std::size_t>(D) * D * D, 0u);
    std::mt19937_64 rng(seed ^ 0x9e3779b97f4a7c15ull);
    std::vector<uint32_t> y2(D), z2(D);
    for (uint32_t u = 0; u < D; ++u) {
      // second representative: random y' in class i, z' = t_{y'} z
      const int i = orbs[u].i;
      std::uniform_int_distribution<uint32_t> d(0, N - 1);
      uint32_t yp;
      do { yp = d(rng); } while (cls[yp] != i);
      y2[u] = yp;
      z2[u] = S1.apply(yp, orbs[u].z);
    }
#pragma omp parallel for schedule(dynamic)
    for (int uu = 0; uu < static_cast<int>(D); ++uu) {
      const uint32_t u = static_cast<uint32_t>(uu);
      const Orbital& U = orbs[u];
      uint32_t* cu = c.data() + static_cast<std::size_t>(u) * D * D;
      uint32_t* cu2 = c2.data() + static_cast<std::size_t>(u) * D * D;
      for (uint32_t w = 0; w < static_cast<uint32_t>(N); ++w) {
        const uint32_t s = id[static_cast<std::size_t>(U.i)][lab[static_cast<std::size_t>(U.i)][w]];
        const uint32_t t = orbital_of(w, U.z);
        ++cu[static_cast<std::size_t>(s) * D + t];
        const uint32_t s2 = orbital_of(y2[u], w);
        const uint32_t t2 = orbital_of(w, z2[u]);
        ++cu2[static_cast<std::size_t>(s2) * D + t2];
      }
    }
    long long bad_rep2 = 0, bad_row = 0, bad_col = 0, bad_sym = 0;
    std::size_t nnz = 0;
    for (uint32_t u = 0; u < D; ++u) {
      const uint32_t* cu = c.data() + static_cast<std::size_t>(u) * D * D;
      const uint32_t* cu2 = c2.data() + static_cast<std::size_t>(u) * D * D;
      if (!std::equal(cu, cu + static_cast<std::size_t>(D) * D, cu2)) ++bad_rep2;
      for (uint32_t s = 0; s < D; ++s) {
        uint64_t row = 0;
        for (uint32_t t = 0; t < D; ++t) { row += cu[static_cast<std::size_t>(s) * D + t]; nnz += cu[static_cast<std::size_t>(s) * D + t] != 0; }
        const uint64_t expect = (orbs[s].i == orbs[u].i) ? orbs[s].osize : 0;
        if (row != expect) ++bad_row;
      }
      for (uint32_t t = 0; t < D; ++t) {
        uint64_t col = 0;
        for (uint32_t s = 0; s < D; ++s) col += cu[static_cast<std::size_t>(s) * D + t];
        // #{w : (w, z) in t} for fixed z of class j(u) = |t| / v_{j(t)} if the column class of t is j(u)
        const uint64_t expect = (orbs[t].j == orbs[u].j) ? orbs[t].size / val[static_cast<std::size_t>(orbs[t].j)] : 0;
        if (col != expect) ++bad_col;
      }
      for (uint32_t s = 0; s < D; ++s)
        for (uint32_t t = 0; t < D; ++t) {
          // |u| c^u_{st} = |s| c^s_{u t^T}
          const uint64_t lhs = orbs[u].size * cu[static_cast<std::size_t>(s) * D + t];
          const uint64_t rhs = orbs[s].size * c[(static_cast<std::size_t>(s) * D + u) * D + orbs[t].transpose];
          if (lhs != rhs) ++bad_sym;
        }
    }
    std::printf("structure constants: %zu nonzero of %u^3; second representatives disagree %lld; row sums bad %lld, column sums bad %lld, "
                "|u| c^u_st = |s| c^s_{u t^T} bad %lld (%.0f ms)\n", nnz, D, bad_rep2, bad_row, bad_col, bad_sym, tc.ms());

    // 8. sets
    struct SetCount { std::string path; std::size_t n; std::vector<uint64_t> cnt; };
    std::vector<SetCount> setcounts;
    for (const auto& sp : sets) {
      Timer ts;
      const std::vector<kiss::Vec> rows = kiss::read_set(sp);
      std::vector<uint32_t> idx;
      for (const auto& r : rows) {
        const int32_t k = L.index_of(r);
        if (k < 0) throw std::runtime_error("set row is not a minimal vector: " + sp.string());
        idx.push_back(static_cast<uint32_t>(k));
      }
      std::vector<uint64_t> cnt(D, 0);
      const int n = static_cast<int>(idx.size());
#pragma omp parallel
      {
        std::vector<uint64_t> loc(D, 0);
        std::vector<uint32_t> moved(static_cast<std::size_t>(n));
#pragma omp for schedule(dynamic)
        for (int a = 0; a < n; ++a) {
          for (int b = 0; b < n; ++b) moved[static_cast<std::size_t>(b)] = S0.apply_inv(idx[static_cast<std::size_t>(a)], idx[static_cast<std::size_t>(b)]);
          for (int b = 0; b < n; ++b)
            for (int q = 0; q < n; ++q) ++loc[orbital_of(moved[static_cast<std::size_t>(b)], moved[static_cast<std::size_t>(q)])];
        }
#pragma omp critical
        for (uint32_t u = 0; u < D; ++u) cnt[u] += loc[u];
      }
      uint64_t tot = 0;
      for (uint64_t v : cnt) tot += v;
      std::printf("set %s: %d vectors, %llu ordered triples counted (n^3 = %lld) (%.0f ms)\n", sp.string().c_str(), n,
                  static_cast<unsigned long long>(tot), static_cast<long long>(n) * n * n, ts.ms());
      setcounts.push_back({sp.string(), static_cast<std::size_t>(n), cnt});
    }

    // JSON
    std::filesystem::create_directories(out.parent_path().empty() ? "." : out.parent_path());
    std::ofstream f(out);
    if (!f) throw std::runtime_error("cannot write " + out.string());
    f << "{\n  \"task\": \"T2.3\",\n";
    f << "  \"description\": \"Orbitals of Stab(x) in Gamma = <Co_0 generators of data/group> on the Leech minimal vectors, "
         "as labels computed from explicit random stabiliser elements (labels refine the true orbitals; equality follows when the "
         "count equals the lower bound from data/scheme/triples.json). Orbital u = (i, o): pairs (y, z) with class(x, y) = i and "
         "z in orbit o of Stab(x, y) (moved to y_i). c[u][s][t] = #{w : (y, w) in s, (w, z) in t} for (y, z) in u.\",\n";
    f << "  \"N\": " << N << ",\n  \"x\": " << x << ",\n  \"seed\": " << seed << ",\n";
    f << "  \"classes\": [-32, -16, -8, 0, 8, 16, 32],\n  \"identity_class\": 6,\n  \"conflict_class\": 5,\n";
    f << "  \"valencies\": [";
    for (int i = 0; i < NC; ++i) f << val[static_cast<std::size_t>(i)] << (i + 1 < NC ? ", " : "");
    f << "],\n  \"representatives\": [";
    for (int i = 0; i < NC; ++i) f << yrep[static_cast<std::size_t>(i)] << (i + 1 < NC ? ", " : "");
    f << "],\n  \"generators\": " << gens.size() << ",\n  \"orbit_of_x\": " << orb << ",\n";
    f << "  \"stab_x_elements\": " << hs.size() << ",\n  \"stab_x_orbits\": " << nx << ",\n";
    f << "  \"stab_xy_elements\": [";
    for (int i = 0; i < NC; ++i) f << nk[static_cast<std::size_t>(i)] << (i + 1 < NC ? ", " : "");
    f << "],\n  \"labels_per_class\": [";
    for (int i = 0; i < NC; ++i) f << nlab[static_cast<std::size_t>(i)] << (i + 1 < NC ? ", " : "");
    f << "],\n  \"D\": " << D << ",\n";
    f << "  \"checks\": {\"s3_involutions_bad\": " << bad_inv << ", \"s3_size_bad\": " << bad_size << ", \"s3_class_bad\": " << bad_cls
      << ", \"second_representative_bad\": " << bad_rep2 << ", \"row_sums_bad\": " << bad_row << ", \"column_sums_bad\": " << bad_col
      << ", \"symmetry_bad\": " << bad_sym << "},\n";
    f << "  \"orbitals_format\": \"[id, i, o, z_rep, j = class(x,z), k = class(y_i,z), size = v_i * orbit_size, orbit_size, transpose_id, swap_xy_id]\",\n";
    f << "  \"orbitals\": [\n";
    for (std::size_t u = 0; u < orbs.size(); ++u) {
      const Orbital& o = orbs[u];
      f << "    [" << u << ", " << o.i << ", " << o.o << ", " << o.z << ", " << o.j << ", " << o.k << ", " << o.size << ", " << o.osize
        << ", " << o.transpose << ", " << o.swap_xy << "]" << (u + 1 < orbs.size() ? ",\n" : "\n");
    }
    f << "  ],\n";
    f << "  \"c_format\": \"[u, s, t, c^u_st] for c > 0\",\n  \"c\": [\n";
    bool first = true;
    for (uint32_t u = 0; u < D; ++u)
      for (uint32_t s = 0; s < D; ++s)
        for (uint32_t t = 0; t < D; ++t) {
          const uint32_t v = c[(static_cast<std::size_t>(u) * D + s) * D + t];
          if (!v) continue;
          f << (first ? "" : ",\n") << "    [" << u << ", " << s << ", " << t << ", " << v << "]";
          first = false;
        }
    f << "\n  ],\n";
    f << "  \"sets\": [\n";
    for (std::size_t q = 0; q < setcounts.size(); ++q) {
      f << "    {\"path\": \"" << setcounts[q].path << "\", \"n\": " << setcounts[q].n << ", \"triples\": [";
      for (uint32_t u = 0; u < D; ++u) f << setcounts[q].cnt[u] << (u + 1 < D ? ", " : "");
      f << "]}" << (q + 1 < setcounts.size() ? ",\n" : "\n");
    }
    f << "  ]\n}\n";
    f.close();
    std::printf("wrote %s\n", out.string().c_str());
    const bool ok = bad_inv == 0 && bad_size == 0 && bad_cls == 0 && bad_rep2 == 0 && bad_row == 0 && bad_col == 0 && bad_sym == 0;
    std::printf("RESULT ok=%d x=%u D=%u labels=%u,%u,%u,%u,%u,%u,%u stab_x_elements=%zu nnz=%zu sets=%zu total_ms=%.0f out=%s\n",
                ok ? 1 : 0, x, D, nlab[0], nlab[1], nlab[2], nlab[3], nlab[4], nlab[5], nlab[6], hs.size(), nnz, sets.size(), total.ms(),
                out.string().c_str());
    return ok ? 0 : 1;
  } catch (const std::exception& ex) {
    std::fprintf(stderr, "triple_orbitals: %s\n", ex.what());
    std::printf("RESULT ok=0 error=1\n");
    return 1;
  }
}
